[package]
name = "rec_aggregation"
version.workspace = true
edition.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
primitives.workspace = true
parallel.workspace = true
pcs.workspace = true
flock.workspace = true
leanvm_core.workspace = true
lean_compiler.workspace = true
xmss.workspace = true
sphincs.workspace = true
lean_da.workspace = true
rand.workspace = true
bincode.workspace = true
serde.workspace = true
tracing.workspace = true

[dev-dependencies]
