# extracted from: https://github.com/leanEthereum/leanSpec

from __future__ import annotations

from typing import Final, Sequence

P: Final = 2**31 - 2**24 + 1
"""KoalaBear prime: `2^31 - 2^24 + 1`."""

BASE_TWO_ADICITY = 24

class Fp:
    """An element of the KoalaBear prime field `F_p`."""

    __slots__ = ("value",)

    def __init__(self, value: int) -> None:
        self.value = value % P

    def __add__(self, other: "Fp") -> "Fp":
        return Fp(self.value + other.value)

    def __sub__(self, other: "Fp") -> "Fp":
        return Fp(self.value - other.value)

    def __neg__(self) -> "Fp":
        return Fp(-self.value)

    def __mul__(self, other: "Fp") -> "Fp":
        return Fp(self.value * other.value)

    def __pow__(self, exponent: int) -> "Fp":
        return Fp(pow(self.value, exponent, P))

    def __eq__(self, other: object) -> bool:
        return isinstance(other, Fp) and self.value == other.value

    def __hash__(self) -> int:
        return hash(self.value)

    def __repr__(self) -> str:
        return f"Fp(value={self.value})"


def quintic_mul(a, b, zero):
    """Schoolbook product in `Fp[X]/(X⁵+X²−1)`. `a`, `b` and the result are length-5
    coefficient lists over any ring sharing the additive identity `zero`."""
    prod = [zero] * 9
    for i in range(5):
        for j in range(5):
            prod[i + j] = prod[i + j] + a[i] * b[j]
    for k in range(8, 4, -1):  # X^k = X^(k−5)·(1 − X²) for k ≥ 5.
        prod[k - 5] = prod[k - 5] + prod[k]
        prod[k - 3] = prod[k - 3] - prod[k]
    return prod[:5]


class EF:
    """Quintic extension `Fp[X] / (X⁵ + X² − 1)`."""

    __slots__ = ("c",)
    DIMENSION = 5

    def __init__(self, coeffs: Sequence[Fp]):
        assert len(coeffs) == 5
        self.c = tuple(coeffs)

    @staticmethod
    def from_base(x: Fp) -> "EF":
        return EF([x, Fp(0), Fp(0), Fp(0), Fp(0)])

    def __add__(self, o):
        if isinstance(o, Fp):
            return EF([self.c[0] + o, *self.c[1:]])
        return EF([a + b for a, b in zip(self.c, o.c)])

    def __sub__(self, o):
        if isinstance(o, Fp):
            return EF([self.c[0] - o, *self.c[1:]])
        return EF([a - b for a, b in zip(self.c, o.c)])

    def __neg__(self):
        return EF([-a for a in self.c])

    __radd__ = __add__

    def __mul__(self, o):
        if isinstance(o, Fp):
            return EF([a * o for a in self.c])
        return EF(quintic_mul(self.c, o.c, Fp(0)))

    __rmul__ = __mul__

    def __eq__(self, o):
        return isinstance(o, EF) and self.c == o.c

    def __hash__(self):
        return hash(self.c)

    def __repr__(self):
        return f"EF({[int(x.value) for x in self.c]})"

    def inv(self) -> "EF":
        result, base, n = ONE, self, P**5 - 2
        while n > 0:
            if n & 1:
                result = result * base
            base = base * base
            n >>= 1
        return result


ZERO = EF([Fp(0)] * 5)
ONE = EF.from_base(Fp(1))


def fb(v: int) -> EF:
    """`EF` lift of an integer base-field element."""
    return EF.from_base(Fp(v))


def ef_sum(terms) -> EF:
    """Sum of an iterable of `EF` (empty -> `ZERO`)."""
    return sum(terms, ZERO)


def ef_prod(factors) -> EF:
    """Product of an iterable of `EF` (empty -> `ONE`)."""
    acc = ONE
    for f in factors:
        acc = acc * f
    return acc


# Plonky3 width-16 circulant MDS first row.
MDS_FIRST_ROW_16: Final = (1, 1, 51, 1, 11, 17, 2, 1, 101, 63, 15, 2, 67, 22, 13, 3)


# KoalaBear two-adic generators: index `b` is a primitive 2^b-th root of unity.
# Built by repeatedly squaring `g[24]` (the canonical generator of the order-2^24
# subgroup): `g[b] = g[b+1]^2 mod P`. Yields `g[1] = -1` and `g[0] = 1`.
KB_TWO_ADIC_GENERATORS: list[int] = [1] * 25
KB_TWO_ADIC_GENERATORS[24] = 0x6AC49F88
for _b in range(23, -1, -1):
    KB_TWO_ADIC_GENERATORS[_b] = pow(KB_TWO_ADIC_GENERATORS[_b + 1], 2, P)
del _b


# 448 raw Poseidon1-KoalaBear width-16 round constants generated by the Grain
# LFSR (Poseidon paper §5.3, parameters field_type=1, α=3, n=31, t=16, R_F=8,
# R_P=20). Reference: https://github.com/Plonky3/Plonky3/blob/main/poseidon1/generate_constants.py
# Layout: 4 initial-full rounds × 16 + 20 partial rounds × 16 + 4 terminal-full rounds × 16.
def _grain_lfsr_round_constants_16() -> tuple[int, ...]:
    bits_msb = lambda v, w: [(v >> (w - 1 - i)) & 1 for i in range(w)]
    state = bits_msb(1, 2) + bits_msb(0, 4) + bits_msb(31, 12) + bits_msb(16, 12) + bits_msb(8, 10) + bits_msb(20, 10) + [1] * 30  # fmt: skip

    def step() -> int:
        nonlocal state
        new = state[62] ^ state[51] ^ state[38] ^ state[23] ^ state[13] ^ state[0]
        state = state[1:] + [new]
        return new

    for _ in range(160):  # spec-mandated warm-up
        step()

    def next_bit() -> int:  # self-shrinking generator: keep step()'s output only when the prior step was 1
        while True:
            if step() == 1:
                return step()
            step()

    def next_fe() -> int:  # rejection sampling into [0, P)
        while True:
            x = 0
            for _ in range(31):
                x = (x << 1) | next_bit()
            if x < P:
                return x

    return tuple(next_fe() for _ in range((8 + 20) * 16))


P1_ROUND_CONSTANTS_16: Final = _grain_lfsr_round_constants_16()


class Poseidon1Params:
    """Parameters for a Poseidon1 instance."""

    __slots__ = ("width", "rounds_f", "rounds_p", "mds_first_row", "round_constants")

    def __init__(
        self,
        width: int,
        rounds_f: int,
        rounds_p: int,
        mds_first_row: Sequence[int],
        round_constants: Sequence[int],
    ) -> None:
        assert len(mds_first_row) == width
        assert len(round_constants) == (rounds_f + rounds_p) * width
        self.width = width
        self.rounds_f = rounds_f
        self.rounds_p = rounds_p
        self.mds_first_row = mds_first_row
        self.round_constants = round_constants


class Poseidon1:
    """Pure-Python Poseidon1 permutation (S-box: x → x^3; dense circulant MDS).

    Round structure: AddRoundConstants → S-box (full state for full rounds, only
    position 0 for partial rounds) → MDS multiply.
    """

    __slots__ = ("_width", "_half_rounds_f", "_rounds_p", "_mds", "_rc")

    def __init__(self, params: Poseidon1Params) -> None:
        self._width = params.width
        self._half_rounds_f = params.rounds_f // 2
        self._rounds_p = params.rounds_p
        n = params.width
        # Build circulant MDS: M[i][j] = first_row[(j - i) mod n].
        self._mds = [[params.mds_first_row[(j - i) % n] for j in range(n)] for i in range(n)]
        self._rc = list(params.round_constants)

    def permute(self, current_state: Sequence[Fp]) -> list[Fp]:
        assert len(current_state) == self._width
        s = [x.value for x in current_state]
        w, p, mds, rc = self._width, P, self._mds, self._rc
        idx = 0

        def mds_mul() -> None:
            new = [sum((mds[i][j] * s[j]) % p for j in range(w)) % p for i in range(w)]
            s[:] = new

        for _ in range(self._half_rounds_f):
            for i in range(w):
                s[i] = (s[i] + rc[idx + i]) % p
            idx += w
            for i in range(w):
                s[i] = (s[i] * s[i] % p) * s[i] % p
            mds_mul()
        for _ in range(self._rounds_p):
            for i in range(w):
                s[i] = (s[i] + rc[idx + i]) % p
            idx += w
            s[0] = (s[0] * s[0] % p) * s[0] % p
            mds_mul()
        for _ in range(self._half_rounds_f):
            for i in range(w):
                s[i] = (s[i] + rc[idx + i]) % p
            idx += w
            for i in range(w):
                s[i] = (s[i] * s[i] % p) * s[i] % p
            mds_mul()

        return [Fp(v) for v in s]


PARAMS_16 = Poseidon1Params(
    width=16,
    rounds_f=8,
    rounds_p=20,
    mds_first_row=MDS_FIRST_ROW_16,
    round_constants=P1_ROUND_CONSTANTS_16,
)
"""Poseidon1 parameters for width-16 (8 full rounds, 20 partial)."""


# ---------------------------------------------------------------------------
# Plonky3 / HorizenLabs partial-round optimization for the AIR.
#
# The AIR circuit verifies the Poseidon1 permutation in a more compact form: for
# the 20 partial rounds, the dense MDS multiply is replaced by a single
# precomputed transition matrix `m_i` (applied once) plus, per round, a
# rank-1-style update parameterized by `sparse_first_row[r]` and `sparse_v[r]`.
# Round constants are similarly compressed into `sparse_first_round_constants`
# (16 elements, added once) and `sparse_scalar_round_constants` (R_P - 1
# scalars, added to position 0 between rounds).
#
# Algorithm follows `crates/backend/koala-bear/src/poseidon1_koalabear_16.rs`
# (`compute_equivalent_matrices`, `equivalent_round_constants`).
# ---------------------------------------------------------------------------


def _mat_mul(a: list[list[int]], b: list[list[int]], n: int) -> list[list[int]]:
    return [[sum(a[i][k] * b[k][j] for k in range(n)) % P for j in range(n)] for i in range(n)]


def _mat_vec(m: list[list[int]], v: Sequence[int], n: int) -> list[int]:
    return [sum(m[i][j] * v[j] for j in range(n)) % P for i in range(n)]


def _mat_transpose(m: list[list[int]], n: int) -> list[list[int]]:
    return [[m[j][i] for j in range(n)] for i in range(n)]


def _gauss_jordan_inv(m_in: list[list[int]], n: int) -> list[list[int]]:
    aug = [row[:] for row in m_in]
    inv = [[1 if i == j else 0 for j in range(n)] for i in range(n)]
    for col in range(n):
        pivot = next(r for r in range(col, n) if aug[r][col] != 0)
        if pivot != col:
            aug[col], aug[pivot] = aug[pivot], aug[col]
            inv[col], inv[pivot] = inv[pivot], inv[col]
        piv_inv = pow(aug[col][col], P - 2, P)
        for j in range(n):
            aug[col][j] = aug[col][j] * piv_inv % P
            inv[col][j] = inv[col][j] * piv_inv % P
        for i in range(n):
            if i == col or aug[i][col] == 0:
                continue
            factor = aug[i][col]
            for j in range(n):
                aug[i][j] = (aug[i][j] - factor * aug[col][j]) % P
                inv[i][j] = (inv[i][j] - factor * inv[col][j]) % P
    return inv


def _compute_air_sparse_constants() -> dict:
    w = PARAMS_16.width
    hf = PARAMS_16.rounds_f // 2
    rp = PARAMS_16.rounds_p
    rc = PARAMS_16.round_constants

    # Dense circulant MDS: M[i][j] = MDS_FIRST_ROW_16[(j - i) mod w].
    mds = [[MDS_FIRST_ROW_16[(j - i) % w] for j in range(w)] for i in range(w)]
    mds_inv = _gauss_jordan_inv(mds, w)
    partial_rc = [list(rc[(hf + i) * w : (hf + i + 1) * w]) for i in range(rp)]

    # --- Compress round constants via backward substitution through MDS^{-1}. ---
    scalar_rc: list[int] = [0] * rp
    tmp = list(partial_rc[rp - 1])
    for i in range(rp - 2, -1, -1):
        inv_cip = _mat_vec(mds_inv, tmp, w)
        scalar_rc[i + 1] = inv_cip[0]
        tmp = list(partial_rc[i])
        for j in range(1, w):
            tmp[j] = (tmp[j] + inv_cip[j]) % P
    sparse_first_round_constants = tmp
    sparse_scalar_round_constants = scalar_rc[1:]  # length rp - 1

    # --- Factor MDS into per-round sparse matrices. ---
    mds_t = _mat_transpose(mds, w)
    m_mul = [row[:] for row in mds_t]
    v_collection: list[list[int]] = []
    w_hat_collection: list[list[int]] = []
    m_i = [[0] * w for _ in range(w)]
    for _ in range(rp):
        v_row = [m_mul[0][j + 1] if j < 15 else 0 for j in range(w)]
        w_col = [m_mul[i + 1][0] for i in range(15)]
        sub = [[m_mul[i + 1][j + 1] for j in range(15)] for i in range(15)]
        m_hat_inv = _gauss_jordan_inv(sub, 15)
        w_hat = [
            sum(m_hat_inv[i][k] * w_col[k] for k in range(15)) % P if i < 15 else 0 for i in range(w)
        ]
        v_collection.append(v_row)
        w_hat_collection.append(w_hat)
        m_i = [row[:] for row in m_mul]
        m_i[0][0] = 1
        for i in range(1, w):
            m_i[i][0] = 0
        for j in range(1, w):
            m_i[0][j] = 0
        m_mul = _mat_mul(mds_t, m_i, w)
    sparse_m_i = _mat_transpose(m_i, w)
    v_collection.reverse()
    w_hat_collection.reverse()

    # Pre-assemble full first rows: [mds[0][0], ŵ[0], ..., ŵ[14]].
    mds_0_0 = mds[0][0]
    sparse_first_row = [[mds_0_0] + w_hat_collection[r][:15] for r in range(rp)]

    return {
        "half_full_rounds": hf,
        "partial_rounds": rp,
        "sparse_m_i": sparse_m_i,
        "sparse_first_row": sparse_first_row,
        "sparse_v": v_collection,
        "sparse_first_round_constants": sparse_first_round_constants,
        "sparse_scalar_round_constants": sparse_scalar_round_constants,
    }


# Precomputed once at module load. Consumed by `verifier._p1c()`.
POSEIDON1_AIR_CONSTANTS = _compute_air_sparse_constants()
