"""Pure-Python verifier for leanVM execution proofs.

Single end-to-end test vector — a rec-aggregation proof over 1000 XMSS
signatures — is generated by the Rust side and stored under `target/`.
Run this script to verify it.

Setup (one-time):
    uv venv .venv --python 3.12
    VIRTUAL_ENV=.venv uv pip install "git+https://github.com/leanEthereum/leanSpec.git"
    cargo test --release -p lean_prover --test dump_whir_configs        -- --nocapture
    cargo test --release -p lean_prover --test dump_poseidon1_constants -- --nocapture
    cargo test --release -p lean_prover --test dump_zkvm_vector         -- --nocapture

Run:
    .venv/bin/python crates/lean_prover/verifier.py

Format:
    .venv/bin/ruff format --line-length 120 crates/lean_prover/verifier.py
"""

from __future__ import annotations

import functools
from dataclasses import dataclass
from typing import Sequence

from lean_spec.subspecs.koalabear import Fp, P
from lean_spec.subspecs.poseidon1 import PARAMS_16, Poseidon1

WHIR_INITIAL_FOLDING_FACTOR, WHIR_SUBSEQUENT_FOLDING_FACTOR = 7, 5
MAX_NUM_VARIABLES_TO_SEND_COEFFS = 8
RS_DOMAIN_INITIAL_REDUCTION_FACTOR = 5
RATE, WIDTH, DIGEST_ELEMS = 8, 16, 8
CAPACITY = WIDTH - RATE

# fmt: off
SNARK_DOMAIN_SEP = [Fp(v) for v in (
    130704175, 1303721200, 493664240, 1035493700,
    2063844858, 1410214009, 1938905908, 1696767928,
)]
# fmt: on

MIN_WHIR_LOG_INV_RATE, MAX_WHIR_LOG_INV_RATE = 1, 4
MIN_LOG_MEMORY_SIZE, MAX_LOG_MEMORY_SIZE = 16, 26
MIN_LOG_N_ROWS_PER_TABLE, MIN_BYTECODE_LOG_SIZE, BASE_TWO_ADICITY = 8, 8, 24
WHIR_CONFIGS_PATH = "whir_configs.json"


class ProofError(Exception):
    pass


class EF:
    """Quintic extension `Fp[X] / (X⁵ + X² − 1)`."""

    __slots__ = ("c",)
    DIMENSION = 5

    def __init__(self, coeffs: Sequence[Fp]):
        assert len(coeffs) == 5
        self.c = tuple(coeffs)

    @staticmethod
    def from_base(x: Fp) -> "EF":
        return EF([x, Fp(0), Fp(0), Fp(0), Fp(0)])

    def __add__(self, o):
        if isinstance(o, Fp):
            return EF([self.c[0] + o, *self.c[1:]])
        return EF([a + b for a, b in zip(self.c, o.c)])

    def __sub__(self, o):
        if isinstance(o, Fp):
            return EF([self.c[0] - o, *self.c[1:]])
        return EF([a - b for a, b in zip(self.c, o.c)])

    def __neg__(self):
        return EF([-a for a in self.c])

    __radd__ = __add__

    def __mul__(self, o):
        if isinstance(o, Fp):
            return EF([a * o for a in self.c])
        return EF(_quintic_mul(self.c, o.c, Fp(0)))

    __rmul__ = __mul__

    def __eq__(self, o):
        return isinstance(o, EF) and self.c == o.c

    def __hash__(self):
        return hash(self.c)

    def __repr__(self):
        return f"EF({[int(x.value) for x in self.c]})"

    def inv(self) -> "EF":
        result, base, n = ONE, self, P**5 - 2
        while n > 0:
            if n & 1:
                result = result * base
            base = base * base
            n >>= 1
        return result


ZERO = EF([Fp(0)] * 5)
ONE = EF.from_base(Fp(1))


def fb(v: int) -> EF:
    """`EF` lift of an integer base-field element."""
    return EF.from_base(Fp(v))


def ef_sum(terms) -> EF:
    """Sum of an iterable of `EF` (empty -> `ZERO`)."""
    return sum(terms, ZERO)


def ef_prod(factors) -> EF:
    """Product of an iterable of `EF` (empty -> `ONE`)."""
    acc = ONE
    for f in factors:
        acc = acc * f
    return acc


def _quintic_mul(a, b, zero):
    """Schoolbook product in `Fp[X]/(X⁵+X²−1)`. `a`, `b` and the result are length-5
    coefficient lists over any ring sharing the additive identity `zero`."""
    prod = [zero] * 9
    for i in range(5):
        for j in range(5):
            prod[i + j] = prod[i + j] + a[i] * b[j]
    for k in range(8, 4, -1):  # X^k = X^(k−5)·(1 − X²) for k ≥ 5.
        prod[k - 5] = prod[k - 5] + prod[k]
        prod[k - 3] = prod[k - 3] - prod[k]
    return prod[:5]


_POSEIDON16 = Poseidon1(PARAMS_16)


def poseidon16_compress_in_place(state: list[Fp]) -> list[Fp]:
    assert len(state) == WIDTH
    return [a + b for a, b in zip(_POSEIDON16.permute(state), state)]


def poseidon16_compress(left: Sequence[Fp], right: Sequence[Fp]) -> list[Fp]:
    return poseidon16_compress_in_place(list(left) + list(right))[:DIGEST_ELEMS]


def hash_slice(data: Sequence[Fp]) -> list[Fp]:
    assert len(data) % RATE == 0 and len(data) >= WIDTH
    state = poseidon16_compress_in_place(list(data[-WIDTH:]))
    for k in range(len(data) // RATE - 3, -1, -1):
        state = poseidon16_compress_in_place(state[:CAPACITY] + list(data[k * RATE : (k + 1) * RATE]))
    return state[:DIGEST_ELEMS]


class Challenger:
    """Duplex-sponge Fiat-Shamir. `observe(chunk)` permutes `state[:CAPACITY] || chunk`;
    `_sample_rate()` reads `state[CAPACITY:]` once per `duplex()`."""

    def __init__(self) -> None:
        self.state: list[Fp] = [Fp(0)] * WIDTH
        self.rate_fresh: bool = False

    def observe(self, chunk: Sequence[Fp]) -> None:
        assert len(chunk) == RATE
        self.state = _POSEIDON16.permute(self.state[:CAPACITY] + list(chunk))
        self.rate_fresh = True

    def observe_many(self, scalars: Sequence[Fp]) -> None:
        for i in range(0, len(scalars), RATE):
            chunk = list(scalars[i : i + RATE])
            chunk += [Fp(0)] * (RATE - len(chunk))
            self.observe(chunk)

    def duplex(self) -> None:
        self.observe([Fp(0)] * RATE)

    def _sample_rate(self) -> list[Fp]:
        assert self.rate_fresh, "stale rate — insert duplex() before sampling"
        self.rate_fresh = False
        return list(self.state[CAPACITY:])

    def _sample_many(self, n: int) -> list[Fp]:
        if n == 0:
            return []
        out = self._sample_rate()
        for _ in range(1, n):
            self.duplex()
            out.extend(self._sample_rate())
        return out

    def sample_vec(self, n: int) -> list[EF]:
        flat = self._sample_many((n * EF.DIMENSION + RATE - 1) // RATE)[: n * EF.DIMENSION]
        return [EF(flat[i : i + EF.DIMENSION]) for i in range(0, len(flat), EF.DIMENSION)]

    def sample(self) -> EF:
        return self.sample_vec(1)[0]

    def sample_in_range(self, bits: int, n_samples: int) -> list[int]:
        assert bits < 31
        flat = self._sample_many((n_samples + RATE - 1) // RATE)[:n_samples]
        return [int(x.value) & ((1 << bits) - 1) for x in flat]


@dataclass
class MerkleOpening:
    leaf_data: list[Fp]
    path: list[list[Fp]]


@dataclass
class Proof:
    transcript: list[Fp]
    merkle_openings: list[MerkleOpening]


class VerifierState(Challenger):
    """Challenger + transcript reader. `n` scalars are consumed as `next_multiple_of(n, RATE)`
    raw scalars (trailing must be zero) and absorbed."""

    def __init__(self, proof: Proof) -> None:
        super().__init__()
        self.transcript = list(proof.transcript)
        self.openings = list(proof.merkle_openings)
        self.offset = 0
        self.open_idx = 0

    def _read_padded(self, n: int) -> list[Fp]:
        n_pad = -(-n // RATE) * RATE
        if self.offset + n_pad > len(self.transcript):
            raise ProofError("ExceededTranscript")
        chunk = self.transcript[self.offset : self.offset + n_pad]
        self.offset += n_pad
        if any(int(chunk[i].value) for i in range(n, n_pad)):
            raise ProofError("InvalidTranscript: non-zero padding")
        self.observe_many(chunk)
        return chunk

    def observe_scalars(self, scalars: Sequence[Fp]) -> None:
        self.observe_many(list(scalars))

    def next_base_scalars_vec(self, n: int) -> list[Fp]:
        return self._read_padded(n)[:n]

    def next_extension_scalars_vec(self, n: int) -> list[EF]:
        flat = self.next_base_scalars_vec(n * EF.DIMENSION)
        return [EF(flat[i : i + EF.DIMENSION]) for i in range(0, len(flat), EF.DIMENSION)]

    def next_extension_scalar(self) -> EF:
        return self.next_extension_scalars_vec(1)[0]

    def next_merkle_opening(self) -> MerkleOpening:
        if self.open_idx >= len(self.openings):
            raise ProofError("ExceededTranscript: no more Merkle openings")
        self.open_idx += 1
        return self.openings[self.open_idx - 1]

    def check_pow_grinding(self, bits: int) -> None:
        if bits == 0:
            return
        self._read_padded(1)
        if int(self.state[CAPACITY].value) & ((1 << bits) - 1) != 0:
            raise ProofError("InvalidGrindingWitness")


_INV_TWO = Fp(pow(2, P - 2, P))


def log2_ceil_usize(x: int) -> int:
    return 0 if x <= 1 else (x - 1).bit_length()


def log2_strict_usize(x: int) -> int:
    assert x > 0 and (x & (x - 1)) == 0, f"{x} is not a power of two"
    return x.bit_length() - 1


def padd_with_zero_to_next_power_of_two(values: Sequence[Fp]) -> list[Fp]:
    if not values:
        return [Fp(0)]
    n = 1 << log2_ceil_usize(len(values))
    return list(values) + [Fp(0)] * (n - len(values))


def merkle_verify_path(
    commit: list[Fp],
    log_height: int,
    index: int,
    opened_values: Sequence[Fp],
    opening_proof: Sequence[list[Fp]],
) -> bool:
    if len(opening_proof) != log_height:
        return False
    cur = hash_slice(list(opened_values))
    for sibling in opening_proof:
        cur = poseidon16_compress(cur, sibling) if index & 1 == 0 else poseidon16_compress(sibling, cur)
        index >>= 1
    return list(commit) == list(cur)


def expand_from_univariate(x: EF, num_variables: int) -> list[EF]:
    """`[x, x², x⁴, …, x^(2^(n−1))]`."""
    out, cur = [], x
    for _ in range(num_variables):
        out.append(cur)
        cur = cur * cur
    return out


def eq_poly_outside(a: Sequence[EF], b: Sequence[EF]) -> EF:
    """`Π (1 − a_i − b_i + 2·a_i·b_i)`."""
    assert len(a) == len(b)
    return ef_prod(ONE + x * y + x * y - x - y for x, y in zip(a, b))


def next_mle(x: Sequence[EF], y: Sequence[EF]) -> EF:
    """Multilinear extension of `y = x + 1` (big-endian, mod `2^n`)."""
    assert len(x) == len(y)
    n = len(x)
    eq_prefix = [ONE]
    for i in range(n):
        eq_prefix.append(eq_prefix[i] * (x[i] * y[i] + (ONE - x[i]) * (ONE - y[i])))
    low_suffix = [ONE] * (n + 1)
    for i in range(n - 1, -1, -1):
        low_suffix[i] = low_suffix[i + 1] * x[i] * (ONE - y[i])
    s = ef_sum(eq_prefix[i] * (ONE - x[i]) * y[i] * low_suffix[i + 1] for i in range(n))
    return s + ef_prod([*x, *y])


def eval_multilinear_evals(evals: Sequence[EF], point: Sequence[EF]) -> EF:
    """Evaluate a multilinear in evaluation form at `point` (big-endian fold)."""
    assert len(evals) == 1 << len(point)
    cur = list(evals)
    for r in reversed(point):
        cur = [cur[j] + (cur[j + 1] - cur[j]) * r for j in range(0, len(cur), 2)]
    return cur[0]


def eval_mle_base_at_ef(base_evals: Sequence[int], point: Sequence[EF]) -> EF:
    """numpy-backed fold for the 2²²-entry bytecode multilinear."""
    import numpy as np

    assert len(base_evals) == 1 << len(point)
    pt = [tuple(int(ci.value) for ci in p.c) for p in point]
    cur = np.asarray(base_evals, dtype=np.int64) % P
    # First round: base → EF. a + (b-a)·r with r ∈ EF.
    a, b = cur[0::2], cur[1::2]
    d = (b - a) % P
    r = pt[-1]
    cur = np.stack(
        [(a + d * r[0]) % P, *[(d * r[k]) % P for k in range(1, 5)]],
        axis=1,
    )
    # EF × EF rounds: schoolbook product reduced mod X⁵+X²−1.
    for r0, r1, r2, r3, r4 in (pt[i] for i in range(len(pt) - 2, -1, -1)):
        a, b = cur[0::2], cur[1::2]
        d = (b - a) % P
        d0, d1, d2, d3, d4 = d[:, 0], d[:, 1], d[:, 2], d[:, 3], d[:, 4]
        m = lambda x, y: (x * y) % P
        p0 = m(d0, r0)
        p1 = (m(d0, r1) + m(d1, r0)) % P
        p2 = (m(d0, r2) + m(d1, r1) + m(d2, r0)) % P
        p3 = (m(d0, r3) + m(d1, r2) + m(d2, r1) + m(d3, r0)) % P
        p4 = (m(d0, r4) + m(d1, r3) + m(d2, r2) + m(d3, r1) + m(d4, r0)) % P
        p5 = (m(d1, r4) + m(d2, r3) + m(d3, r2) + m(d4, r1)) % P
        p6 = (m(d2, r4) + m(d3, r3) + m(d4, r2)) % P
        p7 = (m(d3, r4) + m(d4, r3)) % P
        p8 = m(d4, r4)
        cur = np.stack(
            [
                (a[:, 0] + p0 + p5 - p8) % P,
                (a[:, 1] + p1 + p6) % P,
                (a[:, 2] + p2 - p5 + p7 + p8) % P,
                (a[:, 3] + p3 - p6 + p8) % P,
                (a[:, 4] + p4 - p7) % P,
            ],
            axis=1,
        )
    return EF([Fp(int(v)) for v in cur[0]])


def eval_multilinear_coeffs(coeffs: Sequence[EF], point: Sequence[EF]) -> EF:
    """`Σ_b c_b · Π_i x_i^(b_i)` in the standard multilinear coefficient basis."""
    assert len(coeffs) == 1 << len(point)
    if not point:
        return coeffs[0]
    half = len(coeffs) // 2
    lo = eval_multilinear_coeffs(coeffs[:half], point[1:])
    hi = eval_multilinear_coeffs(coeffs[half:], point[1:])
    return lo + hi * point[0]


@dataclass
class SparseStatement:
    """Claim with multilinear `point` and `(selector, value)` pairs. `is_next`
    swaps the eq-weight for `next_mle`."""

    total_num_variables: int
    point: list[EF]
    values: list[tuple[int, EF]]
    is_next: bool = False

    @property
    def selector_num_variables(self) -> int:
        return self.total_num_variables - len(self.point)

    @staticmethod
    def dense(point: list[EF], value: EF) -> "SparseStatement":
        return SparseStatement(len(point), point, [(0, value)])

    @staticmethod
    def unique_value(total: int, index: int, value: EF) -> "SparseStatement":
        return SparseStatement(total, [], [(index, value)])

    @staticmethod
    def new_next(total: int, point: list[EF], values: list[tuple[int, EF]]) -> "SparseStatement":
        return SparseStatement(total, point, values, is_next=True)


def whir_folding_factor_at_round(r: int) -> int:
    return WHIR_INITIAL_FOLDING_FACTOR if r == 0 else WHIR_SUBSEQUENT_FOLDING_FACTOR


def whir_n_rounds_and_final_sumcheck(num_variables: int) -> tuple[int, int]:
    nv = num_variables - WHIR_INITIAL_FOLDING_FACTOR
    if nv < MAX_NUM_VARIABLES_TO_SEND_COEFFS:
        return 0, nv
    n = -(-(nv - MAX_NUM_VARIABLES_TO_SEND_COEFFS) // WHIR_SUBSEQUENT_FOLDING_FACTOR)
    return n, nv - n * WHIR_SUBSEQUENT_FOLDING_FACTOR


def whir_log_domain_size_at(num_variables: int, start_rate: int, r: int) -> int:
    return num_variables + start_rate - (RS_DOMAIN_INITIAL_REDUCTION_FACTOR + r - 1 if r >= 1 else 0)


# fmt: off
KB_TWO_ADIC_GENERATORS: list[int] = [
    0x1, 0x7F000000, 0x7E010002, 0x6832FE4A, 0x08DBD69C, 0x0A28F031, 0x5C4A5B99,
    0x29B75A80, 0x17668B8A, 0x27AD539B, 0x334D48C7, 0x7744959C, 0x768FC6FA,
    0x303964B2, 0x3E687D4D, 0x45A60E61, 0x6E2F4D7A, 0x163BD499, 0x6C4A8A45,
    0x143EF899, 0x514DDCAD, 0x484EF19B, 0x205D63C3, 0x68E7DD49, 0x6AC49F88,
]
# fmt: on


def two_adic_generator(bits: int) -> Fp:
    return Fp(KB_TWO_ADIC_GENERATORS[bits])


@functools.cache
def whir_config(log_inv_rate: int, num_variables: int) -> dict:
    import json
    from pathlib import Path

    for c in json.loads(Path(__file__).with_name(WHIR_CONFIGS_PATH).read_text()):
        if (c["log_inv_rate"], c["num_variables"]) == (log_inv_rate, num_variables):
            return c
    raise KeyError(
        f"No WHIR config for (log_inv_rate={log_inv_rate}, num_variables={num_variables}). "
        "Regenerate with: cargo test -p lean_prover --test dump_whir_configs"
    )


@dataclass
class ParsedCommitment:
    num_variables: int
    root: list[Fp]  # length DIGEST_ELEMS
    ood_points: list[EF]
    ood_answers: list[EF]

    def oods_constraints(self) -> list[SparseStatement]:
        return [
            SparseStatement.dense(expand_from_univariate(p, self.num_variables), ev)
            for p, ev in zip(self.ood_points, self.ood_answers)
        ]


def _eval_univariate(coeffs: list[EF], x: EF) -> EF:
    acc = ZERO
    for c in reversed(coeffs):
        acc = acc * x + c
    return acc


def verify_sumcheck(
    state: VerifierState, target: EF, n_vars: int, degree: int, pow_bits: int = 0
) -> tuple[list[EF], EF]:
    """Round-by-round: check `h(0) + h(1) == target`, grind, sample, fold. Returns (point, value)."""
    point: list[EF] = []
    for _ in range(n_vars):
        coeffs = state.next_extension_scalars_vec(degree + 1)
        s = coeffs[0] + ef_sum(coeffs)
        if s != target:
            raise ProofError("Sumcheck identity failed: h(0) + h(1) != target")
        state.check_pow_grinding(pow_bits)
        r = state.sample()
        point.append(r)
        target = _eval_univariate(coeffs, r)
    return point, target


def combine_constraints(state: VerifierState, target: EF, constraints: list[SparseStatement]) -> tuple[EF, list[EF]]:
    """Fold all constraint values into `target` via powers of γ; return those γ-power weights."""
    gamma: EF = state.sample()
    combo: list[EF] = []
    g = ONE
    for smt in constraints:
        for _, value in smt.values:
            target = target + g * value
            combo.append(g)
            g = g * gamma
    return target, combo


def verify_stir_challenges(
    state: VerifierState,
    cfg: dict,
    round_index: int,
    num_variables: int,
    folding_factor: int,
    num_queries: int,
    query_pow_bits: int,
    commitment: ParsedCommitment,
    folding_randomness: list[EF],
) -> list[SparseStatement]:
    log_height = whir_log_domain_size_at(cfg["num_variables"], cfg["log_inv_rate"], round_index) - folding_factor
    gen = two_adic_generator(log_height)
    state.check_pow_grinding(query_pow_bits)
    indices = state.sample_in_range(log_height, num_queries)

    def pack_answers(leaf: list[Fp]) -> list[EF]:
        if round_index == 0:
            return [EF.from_base(f) for f in leaf]
        return [EF(leaf[i : i + EF.DIMENSION]) for i in range(0, len(leaf), EF.DIMENSION)]

    constraints: list[SparseStatement] = []
    for idx in indices:
        op = state.next_merkle_opening()
        if not merkle_verify_path(commitment.root, log_height, idx, op.leaf_data, op.path):
            raise ProofError("Merkle verification failed")
        fold = eval_multilinear_evals(pack_answers(op.leaf_data), folding_randomness)
        ef_pt = fb(pow(int(gen.value), idx, P))
        constraints.append(SparseStatement.dense(expand_from_univariate(ef_pt, num_variables), fold))
    return constraints


def verify_constraint_coeffs(constraint: SparseStatement, coeffs: list[EF]) -> bool:
    """Checks `point == [α, α², α⁴, …]` and `Σ coeffs[i]·α^i == value`."""
    assert constraint.selector_num_variables == 0
    alpha = constraint.point[0]
    if any(a * a != b for a, b in zip(constraint.point, constraint.point[1:])):
        return False
    univ_eval = _eval_univariate(coeffs, alpha)
    return all(univ_eval == v[1] for v in constraint.values)


def eval_constraints_poly(constraints: list[tuple[list[EF], list[SparseStatement]]], point: list[EF]) -> EF:
    value = ZERO
    pt = list(point)
    for round_idx, (randomness, smts) in enumerate(constraints):
        if round_idx > 0:
            pt = pt[whir_folding_factor_at_round(round_idx - 1) :]
        i = 0
        for smt in smts:
            inner_pt = pt[len(pt) - len(smt.point) :]
            common = next_mle(smt.point, inner_pt) if smt.is_next else eq_poly_outside(smt.point, inner_pt)
            sel_n = smt.selector_num_variables
            for v in smt.values:
                lagrange = ef_prod(pt[j] if (v[0] >> (sel_n - 1 - j)) & 1 else ONE - pt[j] for j in range(sel_n))
                value = value + lagrange * common * randomness[i]
                i += 1
        assert i == len(randomness)
    return value


def whir_verify(
    state: VerifierState,
    cfg: dict,
    parsed_commitment: ParsedCommitment,
    statement: list[SparseStatement],
) -> list[EF]:
    for s in statement:
        assert s.total_num_variables == parsed_commitment.num_variables

    n_rounds, final_sumcheck_rounds = whir_n_rounds_and_final_sumcheck(cfg["num_variables"])
    round_constraints: list[tuple[list[EF], list[SparseStatement]]] = []
    round_folding: list[list[EF]] = []
    target = ZERO

    def step(constraints: list[SparseStatement], n_fold: int, pow_bits: int) -> None:
        nonlocal target
        state.duplex()
        new_target, combo = combine_constraints(state, target, constraints)
        round_constraints.append((combo, constraints))
        sc_point, target = verify_sumcheck(state, new_target, n_fold, 2, pow_bits)
        round_folding.append(sc_point)

    step(
        parsed_commitment.oods_constraints() + statement,
        whir_folding_factor_at_round(0),
        cfg["starting_folding_pow_bits"],
    )

    prev_commitment = parsed_commitment
    nvars_round = cfg["num_variables"]
    for r in range(n_rounds):
        rp = cfg["rounds"][r]
        nvars_round -= whir_folding_factor_at_round(r)
        nood = rp["ood_samples"]
        new_commitment = ParsedCommitment(
            nvars_round,
            state.next_base_scalars_vec(DIGEST_ELEMS),
            state.sample_vec(nood) if nood else [],
            state.next_extension_scalars_vec(nood) if nood else [],
        )
        stir = verify_stir_challenges(
            state,
            cfg,
            r,
            nvars_round,
            whir_folding_factor_at_round(r),
            rp["num_queries"],
            rp["query_pow_bits"],
            prev_commitment,
            round_folding[-1],
        )
        step(
            new_commitment.oods_constraints() + stir,
            whir_folding_factor_at_round(r + 1),
            rp["folding_pow_bits"],
        )
        prev_commitment = new_commitment

    n_vars_final = nvars_round - whir_folding_factor_at_round(n_rounds)
    final_coeffs = state.next_extension_scalars_vec(1 << n_vars_final)
    final_stir = verify_stir_challenges(
        state,
        cfg,
        n_rounds,
        n_vars_final,
        whir_folding_factor_at_round(n_rounds),
        cfg["final_queries"],
        cfg["final_query_pow_bits"],
        prev_commitment,
        round_folding[-1],
    )
    for smt in final_stir:
        if not verify_constraint_coeffs(smt, final_coeffs):
            raise ProofError("Final STIR constraint mismatch")

    final_sc_point, final_sc_value = verify_sumcheck(state, target, final_sumcheck_rounds, 2)
    round_folding.append(final_sc_point)

    folding_flat = [r for chunk in round_folding for r in chunk]
    eval_weights = eval_constraints_poly(round_constraints, folding_flat)
    final_value = eval_multilinear_coeffs(final_coeffs, list(reversed(final_sc_point)))
    if final_sc_value != eval_weights * final_value:
        raise ProofError("WHIR final sumcheck check failed")

    return folding_flat


@dataclass(frozen=True)
class TableMeta:
    name: str
    n_columns: int
    bus_direction: str  # "Pull" or "Push"
    lookups: tuple[tuple[int, tuple[int, ...]], ...]  # (index_col, value_cols)


def tables_from_json(obj: list[dict]) -> list[TableMeta]:
    return [
        TableMeta(
            name=t["name"],
            n_columns=int(t["n_columns"]),
            bus_direction=t["bus"]["direction"],
            lookups=tuple((int(l["index"]), tuple(int(v) for v in l["values"])) for l in t["lookups"]),
        )
        for t in obj
    ]


def stacked_pcs_global_statements(
    stacked_n_vars: int,
    memory_n_vars: int,
    bytecode_n_vars: int,
    previous_statements: list[SparseStatement],
    table_log_heights: dict[str, int],
    committed_statements: dict[str, list[tuple[list[EF], dict[int, EF], dict[int, EF]]]],
    tables: dict[str, TableMeta],
    constants: dict,
) -> list[SparseStatement]:
    assert len(table_log_heights) == len(committed_statements)
    tables_sorted = sort_tables_by_height(table_log_heights)

    out = list(previous_statements)
    offset = (2 << memory_n_vars) + (1 << max(bytecode_n_vars, tables_sorted[0][1]))
    col_pc = constants["col_pc"]

    # Rust uses BTreeMap (sorted); Python dicts are insertion-ordered, sort here.
    def values_at(d: dict[int, EF], n_vars: int) -> list[tuple[int, EF]]:
        return [((offset >> n_vars) + i, v) for i, v in sorted(d.items())]

    for name, n_vars in tables_sorted:
        if name == "execution":
            # PC column: pin first row to starting_pc, last row to ending_pc.
            for idx, pc in [(0, constants["starting_pc"]), ((1 << n_vars) - 1, constants["ending_pc"])]:
                out.append(SparseStatement.unique_value(stacked_n_vars, offset + (col_pc << n_vars) + idx, fb(pc)))

        for point, eq_values, next_values in committed_statements[name]:
            if next_values:
                out.append(SparseStatement.new_next(stacked_n_vars, list(point), values_at(next_values, n_vars)))
            out.append(SparseStatement(stacked_n_vars, list(point), values_at(eq_values, n_vars)))

        offset += tables[name].n_columns << n_vars

    return out


N_VARS_TO_SEND_GKR_COEFFS = 5


def verify_gkr_quotient(state: VerifierState, n_vars: int) -> tuple[EF, list[EF], EF, EF]:
    """Layered sumcheck for `Σ nᵢ/dᵢ`. Returns `(quotient, point, claim_num, claim_den)`."""
    assert n_vars > N_VARS_TO_SEND_GKR_COEFFS

    nums = state.next_extension_scalars_vec(1 << N_VARS_TO_SEND_GKR_COEFFS)
    dens = state.next_extension_scalars_vec(1 << N_VARS_TO_SEND_GKR_COEFFS)
    quotient = ef_sum(n * d.inv() for n, d in zip(nums, dens))

    point = state.sample_vec(N_VARS_TO_SEND_GKR_COEFFS)
    claim_num = eval_multilinear_evals(nums, point)
    claim_den = eval_multilinear_evals(dens, point)

    for layer_n_vars in range(N_VARS_TO_SEND_GKR_COEFFS, n_vars):
        state.duplex()
        alpha = state.sample()
        raw_pt, sc_value = verify_sumcheck(state, claim_num + alpha * claim_den, layer_n_vars, 3)
        sc_point = list(reversed(raw_pt))
        nl, nr, dl, dr = state.next_extension_scalars_vec(4)
        if sc_value != eq_poly_outside(point, sc_point) * (alpha * dl * dr + nl * dr + nr * dl):
            raise ProofError("GKR step: postponed value mismatch")
        beta = state.sample()
        one_minus = ONE - beta
        claim_num = one_minus * nl + beta * nr
        claim_den = one_minus * dl + beta * dr
        point = sc_point + [beta]

    return quotient, point, claim_num, claim_den


def to_big_endian_in_field(value: int, bit_count: int) -> list[EF]:
    return [ONE if (value >> (bit_count - 1 - i)) & 1 else ZERO for i in range(bit_count)]


def from_end(seq: Sequence, n: int) -> list:
    """The last `n` elements of `seq` (empty list when `n == 0`)."""
    return list(seq[-n:]) if n else []


def mle_of_01234567_etc(point: Sequence[EF]) -> EF:
    """MLE of `f(i) = i` (big-endian) at `point`."""
    if not point:
        return ZERO
    e = mle_of_01234567_etc(point[1:])
    return e + point[0] * fb(1 << (len(point) - 1))


def mle_of_zeros_then_ones(n_zeros: int, point: Sequence[EF]) -> EF:
    """MLE of `[0]*n_zeros ++ [1]*(2^len(point) − n_zeros)` at `point`."""
    n_values = 1 << len(point)
    assert n_zeros <= n_values
    if n_zeros == 0:
        return ONE
    if n_zeros == n_values:
        return ZERO
    half, tail = n_values >> 1, point[1:]
    if n_zeros < half:
        return (ONE - point[0]) * mle_of_zeros_then_ones(n_zeros, tail) + point[0]
    return point[0] * mle_of_zeros_then_ones(n_zeros - half, tail)


def finger_print(discriminator: Fp, data: Sequence[EF], alphas_eq_poly: Sequence[EF]) -> EF:
    """`Σᵢ αᵢ · dataᵢ + α_last · discriminator`."""
    assert len(alphas_eq_poly) > len(data)
    acc = ef_sum(a * d for a, d in zip(alphas_eq_poly, data))
    return acc + alphas_eq_poly[-1] * EF.from_base(discriminator)


def sort_tables_by_height(table_log_heights: dict[str, int]) -> list[tuple[str, int]]:
    """Descending by height, alphabetical on ties (matches Rust `BTreeMap`)."""
    return sorted(sorted(table_log_heights.items()), key=lambda kv: -kv[1])


def eval_eq(point: Sequence[EF]) -> list[EF]:
    """Length-`2^n` evaluation table of `eq(point, ·)`."""
    out = [ONE]
    for p in point:
        out = [w for v in out for w in (v * (ONE - p), v * p)]
    return out


def verify_generic_logup(
    state: VerifierState,
    c: EF,
    alphas: list[EF],
    alphas_eq_poly: list[EF],
    log_memory: int,
    bytecode_multilinear: list[int],
    table_log_heights: dict[str, int],
    tables: dict[str, TableMeta],
    constants: dict,
) -> dict:
    """GKR-quotient + section-by-section (memory/bytecode/per-table) reconstruction."""
    n_instr_cols = constants["n_instruction_columns"]
    n_runtime_cols = constants["n_runtime_columns"]
    col_pc = constants["col_pc"]
    disc_mem = Fp(constants["logup_memory_discriminator"])
    disc_byte = Fp(constants["logup_bytecode_discriminator"])

    tables_sorted = sort_tables_by_height(table_log_heights)
    log_bytecode = log2_strict_usize(len(bytecode_multilinear) // (1 << log2_ceil_usize(n_instr_cols)))
    log_instr = log2_ceil_usize(n_instr_cols)
    log_n_cycles = table_log_heights["execution"]

    table_cols = lambda n: sum(len(vs) for _, vs in tables[n].lookups) + 1
    total_active_len = (
        (1 << log_memory)
        + max(1 << log_bytecode, 1 << tables_sorted[0][1])
        + (1 << log_n_cycles)
        + sum(table_cols(n) << h for n, h in tables_sorted)
    )
    total_gkr_n_vars = log2_ceil_usize(total_active_len)

    quotient, point_gkr, claim_num, claim_den = verify_gkr_quotient(state, total_gkr_n_vars)
    if quotient != ZERO:
        raise ProofError("logup: GKR sum != 0")

    num, den = ZERO, ZERO

    def pref_at(offset: int, log_height: int) -> EF:
        n_missing = total_gkr_n_vars - log_height
        bits = to_big_endian_in_field(offset >> log_height, n_missing)
        return eq_poly_outside(bits, point_gkr[:n_missing])

    # Memory.
    mem_pt = from_end(point_gkr, log_memory)
    pref = pref_at(0, log_memory)
    value_memory_acc = state.next_extension_scalar()
    value_memory = state.next_extension_scalar()
    fp_mem = finger_print(disc_mem, [value_memory, mle_of_01234567_etc(mem_pt)], alphas_eq_poly)
    num = num - pref * value_memory_acc
    den = den + pref * (c - fp_mem)
    offset = 1 << log_memory

    # Bytecode (padded to the tallest table).
    log_byte_pad = max(log_bytecode, tables_sorted[0][1])
    byte_pt = from_end(point_gkr, log_bytecode)
    pref = pref_at(offset, log_bytecode)
    pref_pad = pref_at(offset, log_byte_pad)
    value_bytecode_acc = state.next_extension_scalar()
    bytecode_value = eval_mle_base_at_ef(bytecode_multilinear, list(byte_pt) + list(from_end(alphas, log_instr)))
    correction = ef_prod(ONE - a for a in alphas[: len(alphas) - log_instr])
    fp_byte = (
        bytecode_value * correction
        + mle_of_01234567_etc(byte_pt) * alphas_eq_poly[n_instr_cols]
        + alphas_eq_poly[-1] * EF.from_base(disc_byte)
    )
    num = num - pref * value_bytecode_acc
    den = (
        den
        + pref * (c - fp_byte)
        + pref_pad * mle_of_zeros_then_ones(1 << log_bytecode, from_end(point_gkr, log_byte_pad))
    )
    offset += 1 << log_byte_pad

    # Per-table: execution bytecode lookup + bus column + per-lookup memory reads.
    bus_num_vals: dict[str, EF] = {}
    bus_den_vals: dict[str, EF] = {}
    columns_values: dict[str, dict[int, EF]] = {}
    for name, log_n_rows in tables_sorted:
        meta = tables[name]
        table_values: dict[int, EF] = {}

        if name == "execution":
            eval_on_pc = state.next_extension_scalar()
            instr_evals = state.next_extension_scalars_vec(n_instr_cols)
            table_values[col_pc] = eval_on_pc
            table_values.update({n_runtime_cols + i: e for i, e in enumerate(instr_evals)})
            pref = pref_at(offset, log_n_rows)
            fp = finger_print(disc_byte, list(instr_evals) + [eval_on_pc], alphas_eq_poly)
            num = num + pref
            den = den + pref * (c - fp)
            offset += 1 << log_n_rows

        eval_on_multiplicity = state.next_extension_scalar()
        eval_on_data = state.next_extension_scalar()
        pref = pref_at(offset, log_n_rows)
        num = num + pref * eval_on_multiplicity
        den = den + pref * eval_on_data
        bus_num_vals[name] = eval_on_multiplicity
        bus_den_vals[name] = eval_on_data
        offset += 1 << log_n_rows

        for index_col, value_cols in meta.lookups:
            index_eval = state.next_extension_scalar()
            assert index_col not in table_values
            table_values[index_col] = index_eval
            for i, col_index in enumerate(value_cols):
                value_eval = state.next_extension_scalar()
                assert col_index not in table_values
                table_values[col_index] = value_eval
                pref = pref_at(offset, log_n_rows)
                fp = finger_print(
                    disc_mem,
                    [value_eval, index_eval + fb(i)],
                    alphas_eq_poly,
                )
                num = num + pref
                den = den + pref * (c - fp)
                offset += 1 << log_n_rows

        columns_values[name] = table_values

    den = den + mle_of_zeros_then_ones(offset, point_gkr)
    if num != claim_num:
        raise ProofError("logup: numerators value mismatch")
    if den != claim_den:
        raise ProofError("logup: denominators value mismatch")

    return {
        "value_memory": value_memory,
        "value_memory_acc": value_memory_acc,
        "value_bytecode_acc": value_bytecode_acc,
        "bus_num": bus_num_vals,
        "bus_den": bus_den_vals,
        "gkr_point": list(point_gkr),
        "columns_values": columns_values,
    }


class ConstraintFolder:
    """`flat`/`shift` = current-row / next-row column evals. Each `assert_zero(x)`
    adds `alpha_powers[i]·x` to the accumulator."""

    def __init__(self, flat: Sequence[EF], shift: Sequence[EF], alpha_powers: Sequence[EF]) -> None:
        self.flat, self.shift, self.alpha_powers = (
            list(flat),
            list(shift),
            list(alpha_powers),
        )
        self.accumulator: EF = ZERO
        self.i = 0

    def assert_zero(self, x: EF) -> None:
        self.accumulator = self.accumulator + self.alpha_powers[self.i] * x
        self.i += 1

    def assert_eq(self, x: EF, y: EF) -> None:
        self.assert_zero(x - y)

    def assert_bool(self, x: EF) -> None:
        self.assert_zero(x * (ONE - x))


def _eval_virtual_bus_column(extra_data: dict, multiplicity: EF, discriminator: EF, data: Sequence[EF]) -> EF:
    """`(Σ αᵢ·dataᵢ + α_last·discriminator)·β + multiplicity`.

    The per-bus `discriminator` keeps the three precompile buses disjoint from each
    other and from the memory/bytecode lookups (reserved discriminators 1 and 2)."""
    alphas: list[EF] = extra_data["logup_alphas_eq_poly"]
    bus_beta: EF = extra_data["bus_beta"]
    assert len(data) < len(alphas)
    inner = ef_sum(a * d for a, d in zip(alphas, data)) + alphas[-1] * discriminator
    return inner * bus_beta + multiplicity


def air_constraint_eval(
    table: TableMeta,
    col_evals: Sequence[EF],
    alpha_powers: Sequence[EF],
    extra_data: dict,
) -> EF:
    folder = ConstraintFolder(col_evals[: table.n_columns], col_evals[table.n_columns :], alpha_powers)
    _TABLE_SPECS[table.name]["air"](folder, table, extra_data)
    return folder.accumulator


def _eval_air_execution(folder: ConstraintFolder, table: TableMeta, extra_data: dict) -> None:
    # fmt: off
    (pc, fp, addr_a, addr_b, addr_c, value_a, value_b, value_c,
     operand_a, operand_b, operand_c, flag_a, flag_b, flag_c, flag_c_fp,
     flag_ab_fp, mul, jump, aux, discriminator) = folder.flat[:20]
    # fmt: on
    pc_shift, fp_shift = folder.shift[0], folder.shift[1]

    # nu_x = flag·operand + (1 − flag − flag_ab_fp)·value + flag_ab_fp·(fp + operand)
    nfa = ONE - flag_a - flag_ab_fp
    nfb = ONE - flag_b - flag_ab_fp
    nfc = ONE - flag_c - flag_c_fp
    nu_a = flag_a * operand_a + nfa * value_a + flag_ab_fp * (fp + operand_a)
    nu_b = flag_b * operand_b + nfb * value_b + flag_ab_fp * (fp + operand_b)
    nu_c = flag_c * operand_c + nfc * value_c + flag_c_fp * (fp + operand_c)

    # aux ∈ {0,1,2}: 0=nothing, 1=add, 2=deref.
    add = aux * fb(2) - aux * aux
    deref = aux * (aux - ONE) * EF.from_base(_INV_TWO)
    is_precompile = ONE - add - mul - deref - jump

    az = folder.assert_zero
    az(_eval_virtual_bus_column(extra_data, is_precompile, discriminator, [nu_a, nu_b, nu_c]))
    az(nfa * (addr_a - (fp + operand_a)))
    az(nfb * (addr_b - (fp + operand_b)))
    az(nfc * (addr_c - (fp + operand_c)))
    az(add * (nu_b - (nu_a + nu_c)))
    az(mul * (nu_b - nu_a * nu_c))
    az(deref * (addr_b - (value_a + operand_b)))
    az(deref * (value_b - nu_c))
    jc = jump * nu_a
    az(jc * (nu_a - ONE))
    az(jc * (pc_shift - nu_b))
    az(jc * (fp_shift - nu_c))
    not_jc = ONE - jc
    az(not_jc * (pc_shift - (pc + ONE)))
    az(not_jc * (fp_shift - fp))


# extension_op/air.rs precompile-data layout.
_EXT_OP_FLAG_IS_BE = 4
_EXT_OP_FLAG_ADD = 8
_EXT_OP_FLAG_MUL = 16
_EXT_OP_FLAG_POLY_EQ = 32
_EXT_OP_LEN_MULTIPLIER = 64


def _quintic_mul_ef(a: Sequence[EF], b: Sequence[EF]) -> list[EF]:
    """Multiply two quintic-extension elements whose coefficients are themselves `EF`."""
    assert len(a) == 5 and len(b) == 5
    return _quintic_mul(a, b, ZERO)


def _eval_air_extension_op(folder: ConstraintFolder, table: TableMeta, extra_data: dict) -> None:
    # Layout: shift columns 0..13 = (is_be, start, len, flag_{add,mul,poly_eq},
    # idx_{a,b}, comp[0..5]); then idx_res, va, vb, vres (5 each).
    f = folder.flat
    is_be, start, len_col, flag_add, flag_mul, flag_poly_eq, idx_a, idx_b = f[:8]
    comp, idx_res = f[8:13], f[13]
    va, vb, vres = f[14:19], f[19:24], f[24:29]
    s = folder.shift
    is_be_sh, start_sh, len_sh, flag_add_sh, flag_mul_sh, flag_poly_eq_sh, idx_a_sh, idx_b_sh = s[:8]
    comp_sh = s[8:13]

    aux = (
        is_be * fb(_EXT_OP_FLAG_IS_BE)
        + flag_add * fb(_EXT_OP_FLAG_ADD)
        + flag_mul * fb(_EXT_OP_FLAG_MUL)
        + flag_poly_eq * fb(_EXT_OP_FLAG_POLY_EQ)
        + len_col * fb(_EXT_OP_LEN_MULTIPLIER)
    )
    folder.assert_zero(
        _eval_virtual_bus_column(extra_data, start * (flag_add + flag_mul + flag_poly_eq), aux, [idx_a, idx_b, idx_res])
    )

    for x in (is_be, start, flag_add, flag_mul, flag_poly_eq):
        folder.assert_bool(x)

    is_ee, not_start_sh = ONE - is_be, ONE - start_sh
    va_x = [va[0]] + [va[k] * is_ee for k in range(1, 5)]
    comp_tail = [comp_sh[k] * not_start_sh for k in range(5)]
    va_vb = _quintic_mul_ef(va_x, vb)

    for k in range(5):
        folder.assert_zero((comp[k] - (va_x[k] + vb[k] + comp_tail[k])) * flag_add)
    for k in range(5):
        folder.assert_zero((comp[k] - (va_vb[k] + comp_tail[k])) * flag_mul)

    # poly_eq: comp ← (2·va·vb − va − vb + 1) · comp_sh_or_one.
    poly_eq_val = [va_vb[k] + va_vb[k] - va_x[k] - vb[k] + (ONE if k == 0 else ZERO) for k in range(5)]
    comp_sh_or_one = [comp_sh[0] * not_start_sh + start_sh] + [comp_sh[k] * not_start_sh for k in range(1, 5)]
    poly_eq_result = _quintic_mul_ef(poly_eq_val, comp_sh_or_one)
    for k in range(5):
        folder.assert_zero((comp[k] - poly_eq_result[k]) * flag_poly_eq)
    for k in range(5):
        folder.assert_zero((comp[k] - vres[k]) * start)

    for x, y in [
        (len_col, len_sh + ONE),
        (is_be, is_be_sh),
        (flag_add, flag_add_sh),
        (flag_mul, flag_mul_sh),
        (flag_poly_eq, flag_poly_eq_sh),
    ]:
        folder.assert_zero(not_start_sh * (x - y))

    folder.assert_zero(not_start_sh * (idx_a_sh - idx_a - (is_be + is_ee * fb(5))))
    folder.assert_zero(not_start_sh * (idx_b_sh - idx_b - fb(5)))
    folder.assert_zero(start_sh * (len_col - ONE))


@functools.cache
def _p1c() -> dict:
    import json
    from pathlib import Path

    raw = json.loads(Path(__file__).with_name("poseidon1_constants.json").read_text())
    fp_mat = lambda m: [[Fp(v) for v in row] for row in m]
    fp_vec = lambda v: [Fp(x) for x in v]
    return {
        "half_full_rounds": raw["half_full_rounds"],
        "partial_rounds": raw["partial_rounds"],
        "initial_constants": fp_mat(raw["initial_constants"]),
        "final_constants": fp_mat(raw["final_constants"]),
        "sparse_m_i": fp_mat(raw["sparse_m_i"]),
        "sparse_first_row": fp_mat(raw["sparse_first_row"]),
        "sparse_v": fp_mat(raw["sparse_v"]),
        "sparse_first_rc": fp_vec(raw["sparse_first_round_constants"]),
        "sparse_scalar_rc": fp_vec(raw["sparse_scalar_round_constants"]),
        "mds_dense": fp_mat(raw["mds_dense"]),
    }


_POSEIDON_WIDTH = 16
_HALF_DIGEST_LEN = 4
_POSEIDON_DISCRIMINATOR_BASE = 3  # odd ≥ 3, disjoint from memory (1) / bytecode (2)
_POSEIDON_PERMUTE_SHIFT, _POSEIDON_HALF_OUTPUT_SHIFT = 1 << 1, 1 << 2
_POSEIDON_HARDCODED_LEFT_4_FLAG_SHIFT, _POSEIDON_HARDCODED_LEFT_4_OFFSET_SHIFT = (
    1 << 3,
    1 << 4,
)


def _matvec_kb(mat: list[list[Fp]], state: list[EF]) -> list[EF]:
    return [ef_sum(s * m for s, m in zip(state, row)) for row in mat]


def _full_round(state: list[EF], rc1: list[Fp], rc2: list[Fp]) -> list[EF]:
    for rc in (rc1, rc2):
        sbox = [(t := s + c) * t * t for s, c in zip(state, rc)]
        state = _matvec_kb(_p1c()["mds_dense"], sbox)
    return state


def _eval_poseidon1_16(folder: ConstraintFolder, cols: dict, extra_data: dict) -> None:
    """AIR for Poseidon1-16. Each `post` column commits an intermediate state, which we
    constrain against the local computation, then adopt to bound polynomial degree."""
    const = _p1c()
    state = list(cols["inputs"])
    initial = list(cols["inputs"])
    half_initial = half_final = const["half_full_rounds"] // 2

    for r in range(half_initial):
        state = _full_round(state, const["initial_constants"][2 * r], const["initial_constants"][2 * r + 1])
        for i, post in enumerate(cols["beginning_full_rounds"][r]):
            folder.assert_eq(state[i], post)
            state[i] = post

    state = [s + c for s, c in zip(state, const["sparse_first_rc"])]
    state = _matvec_kb(const["sparse_m_i"], state)

    n_partial = const["partial_rounds"]
    for r in range(n_partial):
        folder.assert_eq(state[0] * state[0] * state[0], cols["partial_rounds"][r])
        state[0] = cols["partial_rounds"][r]
        if r < n_partial - 1:
            state[0] = state[0] + const["sparse_scalar_rc"][r]
        old_s0 = state[0]
        state[0] = ef_sum(state[j] * const["sparse_first_row"][r][j] for j in range(_POSEIDON_WIDTH))
        for i in range(1, _POSEIDON_WIDTH):
            state[i] = state[i] + old_s0 * const["sparse_v"][r][i - 1]

    for r in range(half_final - 1):
        state = _full_round(state, const["final_constants"][2 * r], const["final_constants"][2 * r + 1])
        for i, post in enumerate(cols["ending_full_rounds"][r]):
            folder.assert_eq(state[i], post)
            state[i] = post

    # Last full round: compression mode adds `initial` (gated by flag_half_output for lanes 4..8);
    # permute mode (flag_permute=1) outputs raw state.
    last = 2 * (half_final - 1)
    state = _full_round(state, const["final_constants"][last], const["final_constants"][last + 1])
    flag_permute = cols["flag_permute"]
    not_permute = ONE - flag_permute
    compression_last4 = not_permute - cols["flag_half_output"]
    for i in range(_POSEIDON_WIDTH // 2):
        gate = not_permute if i < _HALF_DIGEST_LEN else compression_last4
        folder.assert_zero(gate * (state[i] + initial[i] - cols["outputs_left"][i]))
        folder.assert_zero(flag_permute * (state[i] - cols["outputs_left"][i]))
        folder.assert_zero(flag_permute * (state[i + _POSEIDON_WIDTH // 2] - cols["outputs_right"][i]))


def _eval_air_poseidon16(folder: ConstraintFolder, table: TableMeta, extra_data: dict) -> None:
    const = _p1c()
    flat, W = folder.flat, _POSEIDON_WIDTH
    half_initial = half_final = const["half_full_rounds"] // 2

    o = 0

    def take(n: int) -> list[EF]:
        nonlocal o
        chunk, o = flat[o : o + n], o + n
        return list(chunk)

    # fmt: off
    [multiplicity, index_b, index_res, flag_half_output, flag_hardcoded_left,
     offset_hardcoded_left, eff_idx_left_first, eff_idx_left_second, flag_permute] = take(9)
    # fmt: on
    inputs = take(W)
    beginning_full_rounds = [take(W) for _ in range(half_initial)]
    partial_cols = take(const["partial_rounds"])
    ending_full_rounds = [take(W) for _ in range(half_final - 1)]
    outputs_left, outputs_right = take(W // 2), take(W // 2)

    discriminator = (
        fb(_POSEIDON_DISCRIMINATOR_BASE)
        + flag_permute * fb(_POSEIDON_PERMUTE_SHIFT)
        + flag_half_output * fb(_POSEIDON_HALF_OUTPUT_SHIFT)
        + flag_hardcoded_left * fb(_POSEIDON_HARDCODED_LEFT_4_FLAG_SHIFT)
        + flag_hardcoded_left * offset_hardcoded_left * fb(_POSEIDON_HARDCODED_LEFT_4_OFFSET_SHIFT)
    )
    not_hcl = ONE - flag_hardcoded_left
    index_a = eff_idx_left_second - not_hcl * fb(_HALF_DIGEST_LEN)

    folder.assert_zero(_eval_virtual_bus_column(extra_data, multiplicity, discriminator, [index_a, index_b, index_res]))
    for f in (multiplicity, flag_half_output, flag_hardcoded_left, flag_permute):
        folder.assert_bool(f)
    folder.assert_zero(flag_permute * (flag_half_output + flag_hardcoded_left))
    folder.assert_zero(flag_hardcoded_left * (offset_hardcoded_left - eff_idx_left_first))
    folder.assert_zero(not_hcl * (index_a - eff_idx_left_first))

    _eval_poseidon1_16(
        folder,
        {
            "inputs": inputs,
            "beginning_full_rounds": beginning_full_rounds,
            "partial_rounds": partial_cols,
            "ending_full_rounds": ending_full_rounds,
            "outputs_left": outputs_left,
            "outputs_right": outputs_right,
            "flag_half_output": flag_half_output,
            "flag_permute": flag_permute,
        },
        extra_data,
    )


_TABLE_SPECS: dict[str, dict] = {
    "execution": {"degree": 5, "n_constraints": 13, "n_shift": 2, "air": _eval_air_execution},
    "extension_op": {"degree": 4, "n_constraints": 33, "n_shift": 13, "air": _eval_air_extension_op},
    "poseidon16_compress": {"degree": 10, "n_constraints": 99, "n_shift": 0, "air": _eval_air_poseidon16},
}


def verify_execution(
    bytecode_hash: list[Fp],
    bytecode_log_size: int,
    public_input: Sequence[Fp],
    proof: Proof,
    tables: Sequence[TableMeta],
    constants: dict,
    bytecode_multilinear: list[int],
) -> dict:
    state = VerifierState(proof)
    state.observe_scalars(list(public_input))
    state.observe_scalars(poseidon16_compress(bytecode_hash, SNARK_DOMAIN_SEP))

    dims = [int(x.value) for x in state.next_base_scalars_vec(3 + len(tables))]
    log_inv_rate, log_memory, public_input_len, *table_log_n_rows = dims
    if public_input_len != len(public_input):
        raise ProofError("InvalidProof: public_input length mismatch")
    if not MIN_WHIR_LOG_INV_RATE <= log_inv_rate <= MAX_WHIR_LOG_INV_RATE:
        raise ProofError("InvalidRate")
    if any(h < MIN_LOG_N_ROWS_PER_TABLE for h in table_log_n_rows):
        raise ProofError("InvalidProof: table too small")
    if log_memory < max(max(table_log_n_rows, default=0), bytecode_log_size):
        raise ProofError("InvalidProof: memory smaller than tables/bytecode")
    if not MIN_LOG_MEMORY_SIZE <= log_memory <= MAX_LOG_MEMORY_SIZE:
        raise ProofError("InvalidProof: log_memory out of range")
    if bytecode_log_size < MIN_BYTECODE_LOG_SIZE:
        raise ProofError("InvalidProof: bytecode too small")

    table_log_heights = {t.name: h for t, h in zip(tables, table_log_n_rows)}
    tables_by_name = {t.name: t for t in tables}
    tables_sorted = sort_tables_by_height(table_log_heights)

    # memory ≥ execution ≥ all other tables.
    if log_memory < table_log_heights["execution"] or table_log_heights["execution"] < tables_sorted[0][1]:
        raise ProofError("InvalidProof: memory or execution table size invariants broken")
    total_stacked = (
        (2 << log_memory)
        + (1 << max(bytecode_log_size, tables_sorted[0][1]))
        + sum(t.n_columns << table_log_heights[t.name] for t in tables)
    )
    stacked_n_vars = log2_ceil_usize(total_stacked)
    if stacked_n_vars > BASE_TWO_ADICITY + WHIR_INITIAL_FOLDING_FACTOR - log_inv_rate:
        raise ProofError("InvalidProof: stacked_n_vars exceeds WHIR domain bound")
    cfg = whir_config(log_inv_rate, stacked_n_vars)
    root = state.next_base_scalars_vec(DIGEST_ELEMS)
    ood_points = state.sample_vec(cfg["commitment_ood_samples"]) if cfg["commitment_ood_samples"] else []
    ood_answers = (
        state.next_extension_scalars_vec(cfg["commitment_ood_samples"]) if cfg["commitment_ood_samples"] else []
    )
    parsed_commitment = ParsedCommitment(stacked_n_vars, root, ood_points, ood_answers)

    logup_c = state.sample()
    state.duplex()
    max_bus_width = 1 + max(constants["max_precompile_bus_width"], constants["n_instruction_columns"])
    logup_alphas = state.sample_vec(log2_ceil_usize(max_bus_width))
    logup_alphas_eq = eval_eq(logup_alphas)
    logup = verify_generic_logup(
        state,
        logup_c,
        logup_alphas,
        logup_alphas_eq,
        log_memory,
        bytecode_multilinear,
        table_log_heights,
        tables_by_name,
        constants,
    )
    gkr_point = logup["gkr_point"]

    bus_beta = state.sample()
    state.duplex()
    air_alpha = state.sample()
    state.duplex()
    eta = state.sample()

    def powers(x: EF, n: int) -> list[EF]:
        out, cur = [], ONE
        for _ in range(n):
            out.append(cur)
            cur = cur * x
        return out

    alpha_powers = powers(air_alpha, max(_TABLE_SPECS[n]["n_constraints"] for n in tables_by_name) + 1)
    eta_powers = powers(eta, len(tables_sorted))
    extra_data = {"logup_alphas_eq_poly": logup_alphas_eq, "bus_beta": bus_beta, "c": logup_c}

    # Initial AIR sum: Σ η^t · (bus_num · sign + β · (bus_den − c)).
    initial_sum = ZERO
    for (name, _), eta_pow in zip(tables_sorted, eta_powers):
        sign = -ONE if tables_by_name[name].bus_direction == "Pull" else ONE
        initial_sum = initial_sum + eta_pow * (
            logup["bus_num"][name] * sign + bus_beta * (logup["bus_den"][name] - logup_c)
        )
    n_max = tables_sorted[0][1]
    sc_point, sc_value = verify_sumcheck(
        state, initial_sum, n_max, max(_TABLE_SPECS[n]["degree"] + 1 for n, _ in tables_sorted)
    )

    committed = {
        name: [(list(from_end(gkr_point, table_log_heights[name])), dict(logup["columns_values"][name]), {})]
        for name in tables_by_name
    }
    my_air_final = ZERO
    for (name, log_n_rows), eta_pow in zip(tables_sorted, eta_powers):
        meta, n_shift = tables_by_name[name], _TABLE_SPECS[name]["n_shift"]
        col_evals = state.next_extension_scalars_vec(meta.n_columns + n_shift)
        constraint_eval = air_constraint_eval(meta, col_evals, alpha_powers, extra_data)

        natural_pt = list(reversed(sc_point[-log_n_rows:])) if log_n_rows else []
        k_t = ef_prod(sc_point[: n_max - log_n_rows])
        my_air_final = (
            my_air_final
            + eta_pow * k_t * eq_poly_outside(from_end(gkr_point, log_n_rows), natural_pt) * constraint_eval
        )

        eq_vals = {i: col_evals[i] for i in range(meta.n_columns)}
        next_vals = {j: col_evals[meta.n_columns + j] for j in range(n_shift)}
        committed[name].append((natural_pt, eq_vals, next_vals))
    if my_air_final != sc_value:
        raise ProofError("AIR sumcheck: claimed value mismatch")

    public_memory = padd_with_zero_to_next_power_of_two(public_input)
    pm_point = state.sample_vec(log2_strict_usize(len(public_memory)))
    pm_eval = eval_multilinear_evals([EF.from_base(f) for f in public_memory], pm_point)

    mk = lambda point, values: SparseStatement(stacked_n_vars, list(point), values)
    previous = [
        mk(from_end(gkr_point, log_memory), [(0, logup["value_memory"]), (1, logup["value_memory_acc"])]),
        mk(pm_point, [(0, pm_eval)]),
        mk(
            from_end(gkr_point, bytecode_log_size),
            [((2 << log_memory) >> bytecode_log_size, logup["value_bytecode_acc"])],
        ),
    ]
    global_statements = stacked_pcs_global_statements(
        stacked_n_vars,
        log_memory,
        bytecode_log_size,
        previous,
        table_log_heights,
        committed,
        tables_by_name,
        constants,
    )
    whir_verify(state, cfg, parsed_commitment, global_statements)

    return {"log_inv_rate": log_inv_rate, "log_memory": log_memory, "stacked_n_vars": stacked_n_vars}


def poseidon_compress_slice_iv(data: Sequence[Fp]) -> list[Fp]:
    """Hash a multiple-of-8 sequence (Poseidon16/Davies-Meyer, all-zero IV)."""
    assert data and len(data) % 8 == 0
    h = [Fp(0)] * 8
    for i in range(0, len(data), 8):
        h = poseidon16_compress(h, list(data[i : i + 8]))
    return h


def main() -> int:
    import array, json
    from pathlib import Path

    vector_path = Path(__file__).resolve().parents[2] / "target" / "zkvm_test_vectors" / "proof.json"
    if not vector_path.exists():
        print(
            f"Test vector not found at {vector_path}. Generate it first with:\n"
            "    cargo test --release -p lean_prover --test dump_zkvm_vector -- --nocapture"
        )
        return 1

    print(f"Loading {vector_path.name}...")
    raw = json.loads(vector_path.read_text())

    arr = array.array("I")
    arr.frombytes((vector_path.parent / raw["bytecode_multilinear_path"]).read_bytes())
    assert len(arr) == raw["bytecode_multilinear_len"]
    bytecode_multilinear: list[int] = list(arr)

    fp_list = lambda xs: [Fp(v) for v in xs]
    public_input = fp_list(raw["public_input"])
    input_data = fp_list(raw["input_data"])
    proof = Proof(
        transcript=fp_list(raw["proof"]["transcript"]),
        merkle_openings=[
            MerkleOpening(leaf_data=fp_list(o["leaf_data"]), path=[fp_list(d) for d in o["path"]])
            for o in raw["proof"]["merkle_openings"]
        ],
    )

    if poseidon_compress_slice_iv(input_data) != public_input:
        print("FAIL: poseidon_compress_slice(input_data) doesn't match dumped public_input")
        return 1

    try:
        result = verify_execution(
            fp_list(raw["bytecode_hash"]),
            raw["bytecode_log_size"],
            public_input,
            proof,
            tables_from_json(raw["tables"]),
            raw["constants"],
            bytecode_multilinear,
        )
    except ProofError as e:
        print(f"FAIL: {e}")
        return 1

    print(f"OK: rec-aggregation proof verified ({result})")
    return 0


if __name__ == "__main__":
    import sys as _sys

    _sys.exit(main())
