[package]
name = "xmss"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[features]
test-utils = ["dep:postcard"]

[dependencies]
rand.workspace = true
backend.workspace = true
serde.workspace = true
postcard = { workspace = true, optional = true }
ssz.workspace = true

[dev-dependencies]
postcard.workspace = true