[package]
name = "pcs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
parallel.workspace = true
primitives.workspace = true
fiat_shamir.workspace = true
zk_alloc.workspace = true
tracing.workspace = true
thiserror.workspace = true

[dev-dependencies]
primitives = { workspace = true, features = ["test-util"] }
bench.workspace = true
bincode.workspace = true

[[bench]]
name = "throughput"
harness = false
