[package]
name = "lean_da"
version.workspace = true
edition.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
primitives.workspace = true
parallel.workspace = true
pcs.workspace = true
fiat_shamir.workspace = true
serde.workspace = true
tracing.workspace = true

[dev-dependencies]
rand.workspace = true
