import Whir.ArrayAlgebra
import Whir.ArrayLayout

/-! Refinement of the actual field-parametric verifier state transitions.
No ring instance is supplied for the concrete UInt64-based extension field. -/
namespace Whir.ReplayRefinement

open Concrete Protocol
open scoped BigOperators

variable {R : Type*} [CommRing R] [Inhabited R]

omit [Inhabited R] in
theorem message_glue_eval (a b : Message R) (ca cb scale r : R) :
    (a.glue b scale).eval (ca + scale * cb) r =
      a.eval ca r + scale * b.eval cb r := by
  simp only [Message.glue, Message.eval]
  ring

theorem foldValues_eq_lane (a : Array R) (block : Nat) (r : R) :
    foldValues a block r = foldLane a block r := by
  unfold foldValues
  split
  · rename_i h
    have hb : block = 1 := by simpa using h
    subst block
    exact (ArrayLayout.foldLane_one a r).symm
  · rfl

/-- The logical meaning of a concrete replay state, including its pending intro. -/
def Represents (state : VerifierState R) (witness : Array R) (block : Nat) : Prop :=
  state.weight.size = witness.size ∧
  state.claim = dot witness state.weight ∧
  state.message = roundMessage witness state.weight block

/-- Exact equality of the pending quadratic update under batching. -/
theorem batch_pending (state : VerifierState R) (basis : Array R)
    (value scale r : R) (intro : Message R) :
    (state.batch basis value scale intro).message.eval
        (state.batch basis value scale intro).claim r =
      state.message.eval state.claim r + scale * intro.eval value r :=
  message_glue_eval _ _ _ _ _ _

/-- The verifier's actual fold transition preserves its interpretation with an
honest pending message and honest next intro, for every aligned lane layout. -/
theorem fold_preserves [CharP R 2] (state : VerifierState R) (f : Array R)
    (block nextBlock lanes : Nat) (r : R) (h : Represents state f block)
    (shape : f.size = (lanes * 2) * block) :
    Represents
      (state.fold block r (roundMessage (foldValues f block r)
        (foldValues state.weight block r) nextBlock))
      (foldValues f block r) nextBlock := by
  refine ⟨?_, ?_, rfl⟩
  · simp only [VerifierState.fold, foldValues_eq_lane, ArrayLayout.size_foldLane, h.1]
  · simp only [VerifierState.fold, h.2.1, h.2.2, foldValues_eq_lane]
    exact ArrayAlgebra.honest_foldLane f state.weight block lanes shape h.1 r

/-- Every nonterminal power-of-two witness with a power-of-two lane block
meets the exact pairing shape, without a restriction on the occupied lanes. -/
theorem fold_preserves_power_of_two [CharP R 2]
    (state : VerifierState R) (f : Array R) (m k nextBlock : Nat) (r : R)
    (h : Represents state f (2 ^ m)) (size : f.size = 2 ^ (m + k + 1)) :
    Represents
      (state.fold (2 ^ m) r (roundMessage (foldValues f (2 ^ m) r)
        (foldValues state.weight (2 ^ m) r) nextBlock))
      (foldValues f (2 ^ m) r) nextBlock := by
  apply fold_preserves state f (2 ^ m) nextBlock (2 ^ k) r h
  rw [size]
  simp [pow_add, Nat.mul_comm, Nat.mul_left_comm]

/-- The actual OOD/query batching transition preserves both the claim and intro
polynomial. The supplied value is the honest inner product, not a postulated
whole-verifier acceptance result. -/
theorem batch_preserves (state : VerifierState R) (f basis : Array R)
    (block lanes : Nat) (scale : R) (h : Represents state f block)
    (shape : f.size = (lanes * 2) * block) (basisSize : basis.size = f.size) :
    Represents
      (state.batch basis (dot f basis) scale (roundMessage f basis block)) f block := by
  refine ⟨?_, ?_, ?_⟩
  · simpa only [VerifierState.batch, ArrayAlgebra.size_weightGlue] using h.1
  · simp only [VerifierState.batch, h.2.1]
    exact (ArrayAlgebra.dot_weightGlue f state.weight basis scale h.1 basisSize).symm
  · simp only [VerifierState.batch, h.2.2]
    exact (ArrayAlgebra.roundMessage_weightGlue f state.weight basis scale block lanes shape h.1).symm

/-- A transcript of the actual fold and batch transitions, with honest messages
generated by the executable array kernels. This does not assume that a resulting
state or verifier accepts. Block changes cover the lane/low and level boundaries. -/
inductive HonestTrace : VerifierState R → Array R → Nat →
    VerifierState R → Array R → Nat → Prop
  | done (state : VerifierState R) (f : Array R) (block : Nat) :
      HonestTrace state f block state f block
  | fold {state finish : VerifierState R} {f result : Array R}
      {block nextBlock endBlock : Nat} (lanes : Nat) (r : R)
      (shape : f.size = (lanes * 2) * block)
      (rest : HonestTrace
        (state.fold block r (roundMessage (foldValues f block r)
          (foldValues state.weight block r) nextBlock))
        (foldValues f block r) nextBlock finish result endBlock) :
      HonestTrace state f block finish result endBlock
  | batch {state finish : VerifierState R} {f result : Array R}
      {block endBlock : Nat} (lanes : Nat) (basis : Array R) (scale : R)
      (shape : f.size = (lanes * 2) * block) (basisSize : basis.size = f.size)
      (rest : HonestTrace
        (state.batch basis (dot f basis) scale (roundMessage f basis block))
        f block finish result endBlock) :
      HonestTrace state f block finish result endBlock

/-- Any number of rounds and level batches preserve the actual array-state
invariant. Remaining obligations are generating this trace from the outer
prover/checking loops and interpreting their authenticated query answers. -/
theorem trace_preserves [CharP R 2]
    {state finish : VerifierState R} {f result : Array R} {block endBlock : Nat}
    (trace : HonestTrace state f block finish result endBlock)
    (initial : Represents state f block) : Represents finish result endBlock := by
  induction trace with
  | done => exact initial
  | fold lanes r shape rest ih =>
    exact ih (fold_preserves _ _ _ _ lanes r initial shape)
  | batch lanes basis scale shape basisSize rest ih =>
    exact ih (batch_preserves _ _ basis _ lanes scale initial shape basisSize)

/-- The actual terminal Boolean comparison accepts an invariant-preserving scalar
state when the supplied final evaluation is that scalar witness. -/
theorem terminal_complete [BEq R] [LawfulBEq R]
    (state : VerifierState R) (witness : Array R) (value : R)
    (hs : witness.size = 1) (hw : state.weight.size = witness.size)
    (hc : state.claim = dot witness state.weight) (hv : value = witness[0]!) :
    state.checkTerminal value = true := by
  simp only [VerifierState.checkTerminal, beq_iff_eq]
  rw [hc, ArrayAlgebra.dot_eq_sum, hw, hs]
  simp only [Nat.min_self, Finset.sum_range_one]
  rw [hv]

/-- Honest actual array messages, through arbitrary folds and level batches,
pass the actual terminal Boolean checker once one witness scalar remains. -/
theorem trace_terminal [CharP R 2] [BEq R] [LawfulBEq R]
    (f weight : Array R) (block : Nat) (sameSize : weight.size = f.size)
    {finish : VerifierState R} {result : Array R} {endBlock : Nat}
    (trace : HonestTrace ⟨weight, dot f weight, roundMessage f weight block⟩
      f block finish result endBlock) (scalar : result.size = 1) :
    finish.checkTerminal result[0]! = true := by
  have h := trace_preserves trace ⟨sameSize, rfl, rfl⟩
  exact terminal_complete finish result result[0]! scalar h.1 h.2.1 rfl

end Whir.ReplayRefinement
