import Whir.RingSwitch
import Whir.OODBounds
import Whir.RingMapInjectivity

/-! Six-stage ring-map expansion and its challenge-polynomial bounds.

The enumeration is generated by `RingSwitch.composedMap`'s actual stage order.
Kernel-checked finite certificates identify its 64 distinct monomials with the
Annex A coefficient formula and certify their exact maximum degree.

Nonvanishing uses a stronger direct Frobenius/Vandermonde argument from
`RingMapInjectivity`: raising the kth zero pairing to `2^(63-k)` produces one
degree-at-most-63 polynomial over the extension field with 64 distinct roots.
Consequently the Annex's cubic-basis split is unnecessary as a prerequisite.
Concrete instantiation still requires exact characteristic-two field operations,
the base-field embedding, 64 distinct conjugates of the represented base
generator, and (for the numeric 192-bit bound) the extension's cardinality.
Neither discrepancy nonvanishing nor any probability bound is assumed. -/
namespace Whir.RingMapSoundness
open scoped BigOperators
open MvPolynomial

abbrev Term := (Fin 6 → ℕ) × ℕ

def nextTerm (p : Fin 6) (t : Term) : Term :=
  (fun i => (if i = p then 1 else 0) + 2 ^ (2 ^ (5 - p.val)) * t.1 i,
    2 ^ (5 - p.val) + t.2)

def nextTerms (p : Fin 6) (ts : List Term) : List Term :=
  ts ++ ts.map (nextTerm p)

def terms : List Term :=
  (List.finRange 6).foldl (fun ts p => nextTerms p ts) [(fun _ => 0, 0)]

noncomputable def exponent (t : Term) : Fin 6 →₀ ℕ :=
  Finsupp.equivFunOnFinite.symm t.1

variable {E : Type*} [CommRing E] [CharP E 2]

noncomputable def termPolynomial (a : E) (t : Term) : MvPolynomial (Fin 6) E :=
  monomial (exponent t) (a ^ (2 ^ t.2))

noncomputable def termsPolynomial (a : E) (ts : List Term) : MvPolynomial (Fin 6) E :=
  (ts.map (termPolynomial a)).sum

theorem exponent_next (p : Fin 6) (t : Term) :
    exponent (nextTerm p t) = Finsupp.single p 1 +
      2 ^ (2 ^ (5 - p.val)) • exponent t := by
  classical
  ext i
  simp [exponent, nextTerm, Finsupp.single_apply, eq_comm]

omit [CharP E 2] in
theorem termPolynomial_next (a : E) (p : Fin 6) (t : Term) :
    termPolynomial a (nextTerm p t) =
      X p * termPolynomial a t ^ (2 ^ (2 ^ (5 - p.val))) := by
  rw [termPolynomial, exponent_next]
  simp only [termPolynomial, X, monomial_pow, monomial_mul_monomial, one_mul]
  congr 1
  simp [nextTerm, pow_mul, Nat.pow_add, Nat.mul_comm]

theorem stage_termsPolynomial (a : E) (p : Fin 6) (ts : List Term) :
    RingSwitch.stage (X p) (2 ^ (5 - p.val)) (termsPolynomial a ts) =
      termsPolynomial a (nextTerms p ts) := by
  simp only [RingSwitch.stage, AddMonoidHom.coe_mk, ZeroHom.coe_mk,
    termsPolynomial, nextTerms, List.map_append, List.sum_append,
    list_sum_pow_char_pow, List.map_map]
  congr 1
  induction ts with
  | nil => simp
  | cons t ts ih =>
    simp only [List.map_cons, List.sum_cons, mul_add, Function.comp_apply,
      ← termPolynomial_next, ih]

theorem fold_apply (ps : List (Fin 6)) (φ : E →+ E) (f : Fin 6 → E) (a : E) :
    (ps.foldl (fun φ p => (RingSwitch.stage (f p) (2 ^ (5 - p.val))).comp φ) φ) a =
      ps.foldl (fun b p => RingSwitch.stage (f p) (2 ^ (5 - p.val)) b) (φ a) := by
  induction ps generalizing φ with
  | nil => rfl
  | cons p ps ih =>
    simpa only [List.foldl_cons, AddMonoidHom.comp_apply] using
      (ih ((RingSwitch.stage (f p) (2 ^ (5 - p.val))).comp φ))

theorem fold_expansion (a : E) (ps : List (Fin 6)) (ts : List Term) :
    (ps.foldl (fun φ p => (RingSwitch.stage (X p) (2 ^ (5 - p.val))).comp φ)
      (AddMonoidHom.id _)) (termsPolynomial a ts) =
      termsPolynomial a (ps.foldl (fun ts p => nextTerms p ts) ts) := by
  rw [fold_apply]
  simp only [AddMonoidHom.id_apply]
  induction ps generalizing ts with
  | nil => rfl
  | cons p ps ih =>
    simpa only [List.foldl_cons, stage_termsPolynomial] using ih (nextTerms p ts)


/-- The list is generated by the actual stage order, not by an independent
coefficient sampler. All combinatorial checks below reduce in the kernel. -/
theorem terms_length : terms.length = 64 := by decide

theorem terms_exponents_distinct : (terms.map Prod.fst).Nodup := by decide

theorem terms_shifts : ∀ k : Fin 64, ∃ t ∈ terms, t.2 = k.val := by decide

theorem terms_shift_range : ∀ t ∈ terms, t.2 < 64 := by decide

/-- Annex A's closed coefficient formula, certified for every generated term. -/
theorem terms_closed_formula : ∀ t ∈ terms, ∀ p : Fin 6,
    t.1 p = if t.2 / 2 ^ (5 - p.val) % 2 = 1
      then 2 ^ (t.2 % 2 ^ (5 - p.val)) else 0 := by decide

theorem terms_max_degree : ∃ t ∈ terms, t.2 = 63 ∧
    (∑ p : Fin 6, t.1 p) = 2^31 + 2^15 + 2^7 + 2^3 + 2 + 1 := by decide

theorem terms_degree : ∀ t ∈ terms,
    (∑ p : Fin 6, t.1 p) ≤ 2^31 + 2^15 + 2^7 + 2^3 + 2 + 1 := by decide

theorem degree_budget : 2^31 + 2^15 + 2^7 + 2^3 + 2 + 1 < (2:ℕ)^32 := by norm_num

theorem composedMap_symbolic (a : E) :
    RingSwitch.composedMap (fun p => (X p : MvPolynomial (Fin 6) E)) (C a) =
      termsPolynomial a terms := by
  have h := fold_expansion a (List.finRange 6) [(fun _ => 0, 0)]
  have h0 : termsPolynomial a [(fun _ => 0, 0)] = C a := by
    have hz : exponent ((fun _ => 0), 0) = 0 := by ext p; simp [exponent]
    simp [termsPolynomial, termPolynomial, hz]
  rw [h0] at h
  exact h

theorem eval_composedMap (a : E) (f : Fin 6 → E) :
    eval f (RingSwitch.composedMap (fun p => (X p : MvPolynomial (Fin 6) E)) (C a)) =
      RingSwitch.composedMap f a := by
  simp only [RingSwitch.composedMap, fold_apply, AddMonoidHom.id_apply]
  generalize List.finRange 6 = ps
  have h (ps : List (Fin 6)) (b : MvPolynomial (Fin 6) E) :
      eval f (ps.foldl (fun b p => RingSwitch.stage (X p) (2 ^ (5 - p.val)) b) b) =
        ps.foldl (fun b p => RingSwitch.stage (f p) (2 ^ (5 - p.val)) b) (eval f b) := by
    induction ps generalizing b with
    | nil => rfl
    | cons p ps ih =>
      simp only [List.foldl_cons, ih]
      congr 1
      simp [RingSwitch.stage]
  simpa using h ps (C a)

theorem terms_nodup : terms.Nodup := List.Nodup.of_map _ terms_exponents_distinct

theorem exponent_injective_on (s : Term) (hs : s ∈ terms) (t : Term) (ht : t ∈ terms)
    (h : exponent s = exponent t) : s = t := by
  apply (List.nodup_map_iff_inj_on terms_nodup).mp terms_exponents_distinct s hs t ht
  exact Finsupp.equivFunOnFinite.symm.injective h

omit [CharP E 2] in
theorem termsPolynomial_sum (a : E) :
    termsPolynomial a terms = ∑ t ∈ terms.toFinset, termPolynomial a t := by
  classical
  exact (List.sum_toFinset _ terms_nodup).symm

/-- The actual implementation is a sum of 64 distinct challenge monomials,
with the Frobenius index and each challenge exponent given above. -/
theorem composedMap_expansion (a : E) (f : Fin 6 → E) :
    RingSwitch.composedMap f a =
      ∑ t ∈ terms.toFinset, (a ^ (2 ^ t.2)) * ∏ p : Fin 6, f p ^ t.1 p := by
  rw [← eval_composedMap, composedMap_symbolic, termsPolynomial_sum, map_sum]
  apply Finset.sum_congr rfl
  intro t _
  simp [termPolynomial, eval_monomial, exponent, Finsupp.prod_fintype]

omit [CharP E 2] in
theorem coeff_termsPolynomial (a : E) (t : Term) (ht : t ∈ terms) :
    (termsPolynomial a terms).coeff (exponent t) = a ^ (2 ^ t.2) := by
  classical
  rw [termsPolynomial_sum, coeff_sum]
  rw [Finset.sum_eq_single t]
  · simp [termPolynomial]
  · intro s hs hne
    simp only [termPolynomial, coeff_monomial]
    split_ifs with h
    · exact (hne (exponent_injective_on s (List.mem_toFinset.mp hs) t ht h)).elim
    · rfl
  · simp [ht]

omit [CharP E 2] in
theorem termsPolynomial_degree (a : E) :
    (termsPolynomial a terms).totalDegree ≤ 2^31 + 2^15 + 2^7 + 2^3 + 2 + 1 := by
  classical
  rw [termsPolynomial_sum]
  apply (totalDegree_finsetSum _ _).trans
  apply Finset.sup_le
  intro t ht
  apply (totalDegree_monomial_le (exponent t) (a ^ (2 ^ t.2))).trans
  rw [Finsupp.sum_fintype _ _ (fun _ => rfl)]
  exact terms_degree t (List.mem_toFinset.mp ht)

/-- Fixed slice errors give an actual six-challenge polynomial. -/
noncomputable def discrepancyPolynomial (basis errors : Fin 64 → E) :
    MvPolynomial (Fin 6) E :=
  ∑ i, C (basis i) * termsPolynomial (errors i) terms

theorem discrepancy_eval (basis errors : Fin 64 → E) (f : Fin 6 → E) :
    eval f (discrepancyPolynomial basis errors) =
      ∑ i, basis i * RingSwitch.composedMap f (errors i) := by
  simp only [discrepancyPolynomial, map_sum, map_mul, eval_C,
    ← composedMap_symbolic, eval_composedMap]

omit [CharP E 2] in
theorem discrepancy_coeff (basis errors : Fin 64 → E) (t : Term) (ht : t ∈ terms) :
    (discrepancyPolynomial basis errors).coeff (exponent t) =
      ∑ i, basis i * errors i ^ (2 ^ t.2) := by
  simp only [discrepancyPolynomial, coeff_sum, coeff_C_mul, coeff_termsPolynomial _ t ht]

omit [CharP E 2] in
theorem discrepancy_degree (basis errors : Fin 64 → E) :
    (discrepancyPolynomial basis errors).totalDegree ≤ 2^31 + 2^15 + 2^7 + 2^3 + 2 + 1 := by
  apply (totalDegree_finsetSum _ _).trans
  apply Finset.sup_le
  intro i _
  exact (totalDegree_mul _ _).trans (by simpa using termsPolynomial_degree (errors i))

/-- The dishonest-minus-honest family target is precisely the discrepancy
tested below. In particular each batching scale remains inside the map. -/
theorem family_target_discrepancy {J : Type*} [Fintype J]
    (f : Fin 6 → E) (basis : Fin 64 → E) (scales : J → E)
    (sent honest : J → Fin 64 → E) :
    RingSwitch.familyTarget (RingSwitch.composedMap f) basis scales sent -
      RingSwitch.familyTarget (RingSwitch.composedMap f) basis scales honest =
      ∑ i, basis i * RingSwitch.composedMap f
        (∑ j, scales j * (sent j i - honest j i)) := by
  simp only [RingSwitch.familyTarget, mul_sub, Finset.sum_sub_distrib, map_sub]

section Field
variable {F : Type*} [Field F] [CharP F 2]

/-- Distinct base-field conjugates, rather than an assumed nonzero discrepancy,
force a nonzero coefficient in the actual six-stage challenge polynomial. -/
theorem discrepancy_ne_zero (x : F)
    (conjugates : Function.Injective (fun k : Fin 64 => x ^ (2 ^ k.val)))
    (errors : Fin 64 → F) (hne : errors ≠ 0) :
    discrepancyPolynomial (fun i => x ^ i.val) errors ≠ 0 := by
  obtain ⟨k, hk⟩ := RingMapInjectivity.exists_nonzero_pairing x conjugates errors hne
  obtain ⟨t, ht, htk⟩ := terms_shifts k
  intro h
  have hc := congrArg (fun p : MvPolynomial (Fin 6) F => p.coeff (exponent t)) h
  simp only [discrepancy_coeff _ _ t ht, htk] at hc
  exact hk hc

variable [Fintype F] [DecidableEq F]

/-- Six independent uniform challenges: soundness follows from the actual map,
its 64 distinct monomials, conjugate injectivity, and Schwartz--Zippel. -/
theorem map_error_probability (x : F)
    (conjugates : Function.Injective (fun k : Fin 64 => x ^ (2 ^ k.val)))
    (errors : Fin 64 → F) (hne : errors ≠ 0) :
    Soundness.uniformProb (Finset.univ.filter fun f : Fin 6 → F =>
      (∑ i : Fin 64, x ^ i.val * RingSwitch.composedMap f (errors i)) = 0) ≤
        ((2:ℚ)^32) / Fintype.card F := by
  classical
  have hp := discrepancy_ne_zero x conjugates errors hne
  have hs := schwartz_zippel_totalDegree hp (Finset.univ : Finset F)
  simp [discrepancy_eval] at hs
  have hs' :
      ((Finset.univ.filter fun f : Fin 6 → F =>
        (∑ i : Fin 64, x ^ i.val * RingSwitch.composedMap f (errors i)) = 0).card : ℚ) /
          (Fintype.card F : ℚ)^6 ≤
        ((discrepancyPolynomial (fun i => x ^ i.val) errors).totalDegree : ℚ) /
          Fintype.card F := by exact_mod_cast hs
  have hd : (discrepancyPolynomial (fun i => x ^ i.val) errors).totalDegree ≤ (2:ℕ)^32 :=
    (discrepancy_degree _ _).trans degree_budget.le
  unfold Soundness.uniformProb
  simpa [Fintype.card_fun] using hs'.trans
    (div_le_div_of_nonneg_right (by exact_mod_cast hd) (by positivity))

/-- The base/extension bridge needs an exact ring embedding and distinct base
conjugates; it does not need a new map-correctness or cubic-independence axiom. -/
theorem map_error_probability_over_base {K : Type*} [Field K]
    (φ : K →+* F) (x : K)
    (conjugates : Function.Injective (fun k : Fin 64 => x ^ (2 ^ k.val)))
    (errors : Fin 64 → F) (hne : errors ≠ 0) :
    Soundness.uniformProb (Finset.univ.filter fun f : Fin 6 → F =>
      (∑ i : Fin 64, φ (x ^ i.val) * RingSwitch.composedMap f (errors i)) = 0) ≤
        ((2:ℚ)^32) / Fintype.card F := by
  simpa only [map_pow] using
    map_error_probability (φ x) (RingMapInjectivity.conjugates_map φ x conjugates) errors hne

/-- The error list is a fixed input, not a function of the six challenges.
This is the union bound used after commitment-fixed list decoding. -/
theorem map_error_fixed_list (x : F)
    (conjugates : Function.Injective (fun k : Fin 64 => x ^ (2 ^ k.val)))
    (errors : Finset (Fin 64 → F)) (nonzero : ∀ e ∈ errors, e ≠ 0) :
    Soundness.uniformProb (Finset.univ.filter fun f : Fin 6 → F =>
      ∃ e ∈ errors, (∑ i : Fin 64, x ^ i.val * RingSwitch.composedMap f (e i)) = 0) ≤
        (errors.card : ℚ) * (((2:ℚ)^32) / Fintype.card F) := by
  classical
  let events : ↥errors → Finset (Fin 6 → F) := fun e =>
    Finset.univ.filter fun f => (∑ i : Fin 64, x ^ i.val *
      RingSwitch.composedMap f (e.val i)) = 0
  have he : (Finset.univ.filter fun f : Fin 6 → F =>
      ∃ e ∈ errors, (∑ i : Fin 64, x ^ i.val * RingSwitch.composedMap f (e i)) = 0) =
      Finset.univ.biUnion events := by
    ext f
    simp [events]
  rw [he]
  calc
    _ ≤ ∑ e, Soundness.uniformProb (events e) := Soundness.union_bound events
    _ ≤ ∑ _e : ↥errors, (((2:ℚ)^32) / Fintype.card F) :=
      Finset.sum_le_sum fun e _ => map_error_probability x conjugates e.val (nonzero e.val e.property)
    _ = _ := by simp

end Field

end Whir.RingMapSoundness
