import Whir.WHIRPhysicalVerifier

namespace Whir.WHIRPhysicalRowsRegression
open Concrete FiatShamirGame MerkleTransport MerkleTransport.Commitments MerkleBinding

private def padded : List K := List.replicate 63 0 ++ [7]
private def snapshot : Snapshot := ⟨{ByteCodec.wordsBytes padded},[]⟩
private def root : Digest32 := PublicMerkleLog.hashBlake2s (ByteCodec.wordsBytes padded)

private theorem single_leaf_extracted (hash : Primitive) (stored : List K) :
    row hash ⟨{ByteCodec.wordsBytes stored},[]⟩ (hash (ByteCodec.wordsBytes stored)) 0 0 = stored := by
  classical
  let H := hashing hash
  have existsPath : ∃ path : Opening (List K) Digest32 [],
      path.inputs H ⊆ {ByteCodec.wordsBytes stored} ∧
        path.digest H = hash (ByteCodec.wordsBytes stored) :=
    ⟨.leaf stored,by simp [Opening.inputs,H,hashing],rfl⟩
  change idealRow H {ByteCodec.wordsBytes stored} (hash (ByteCodec.wordsBytes stored)) [] [] = stored
  unfold idealRow
  rw [dite_eq_left existsPath]
  have recorded := existsPath.choose_spec.1
  cases chosen : existsPath.choose with
  | leaf words =>
    have member : ByteCodec.wordsBytes words ∈ ({ByteCodec.wordsBytes stored} : Finset (List Byte)) :=
      recorded (by rw [chosen]; simp [Opening.inputs,H,hashing])
    exact ByteCodec.wordsBytes_injective (Finset.mem_singleton.mp member)

private theorem extracted : row PublicMerkleLog.hashBlake2s snapshot root 0 0 = padded :=
  single_leaf_extracted _ _

/-- An occupied nonzero lane must survive the full padded leaf extraction. -/
example : WHIRPhysicalRows.compactBaseRow PublicMerkleLog.hashBlake2s snapshot root 0 0 64 1 = [7] := by
  rw [WHIRPhysicalRows.compactBaseRow,baseRow,extracted]
  norm_num [padded]

/-- The old caller supplied the occupied width to a full-leaf normalizer. -/
example : baseRow PublicMerkleLog.hashBlake2s snapshot root 0 0 1 = [0] := by
  rw [baseRow,extracted]
  norm_num [padded]

private def fullWords : List K := [9,4,2,7]
private def fullSnapshot : Snapshot := ⟨{ByteCodec.wordsBytes fullWords},[]⟩
private def fullRoot : Digest32 := PublicMerkleLog.hashBlake2s (ByteCodec.wordsBytes fullWords)

private theorem full_width_row :
    WHIRPhysicalRows.compactBaseRow PublicMerkleLog.hashBlake2s fullSnapshot fullRoot 0 0 4 4 =
      [9,4,2,7] := by
  have h : row PublicMerkleLog.hashBlake2s fullSnapshot fullRoot 0 0 = fullWords :=
    single_leaf_extracted _ _
  rw [WHIRPhysicalRows.compactBaseRow,baseRow,h]
  norm_num [fullWords]

/-- Raw full-width rows are not reversed by extraction; the consumer reverses once. -/
example :
    (WHIRPhysicalRows.compactBaseRow PublicMerkleLog.hashBlake2s fullSnapshot fullRoot 0 0 4 4).reverse =
      [7,2,4,9] := by
  rw [full_width_row]
  rfl

/-- Expected leaf values and digests are independent fixtures. Digests were
cross-checked with Python hashlib.blake2s, not generated by the verifier. -/
def smoke : IO Unit := do
  let fixtures : List (List K × Nat × List K × List K × List Nat) :=
    [([7],64,List.replicate 63 0 ++ [7],[7],
      [0x2d,0xc2,0x41,0xa9,0x1b,0xcd,0xd5,0x13,0x9f,0xcd,0x55,0xd3,0xe9,0x31,0xb4,0xc3,
       0x23,0xe6,0x61,0x93,0x16,0x22,0xc4,0xf8,0x93,0x69,0xc2,0x78,0x08,0xc1,0xa6,0xb2]),
     ([9,4,2,7],4,[9,4,2,7],[7,2,4,9],
      [0x3a,0x6d,0x57,0x71,0xfd,0xb1,0xea,0x1e,0x22,0x70,0x3a,0x54,0xbb,0xb3,0x42,0x12,
       0x74,0x28,0x86,0x56,0x16,0x74,0x18,0x31,0x0c,0xf4,0x85,0x0f,0xd0,0x9c,0x49,0x58])]
  for (stored,width,expectedImage,expectedFold,digest) in fixtures do
    let committed := PublicMerkleLog.hashBlake2s (ByteCodec.wordsBytes expectedImage)
    unless (List.ofFn committed).map Fin.val == digest do
      throw (IO.userError "ordinary BLAKE2s leaf digest differs from independent fixture")
    let proof : PrunedMerklePaths := ⟨[stored],[]⟩
    match proof.open PublicMerkleLog.hashBlake2s committed 1 [0,0] stored.length width with
    | none => throw (IO.userError "actual pruned leaf parser rejected a valid occupied row")
    | some paths =>
      unless paths.length == 2 do throw (IO.userError "duplicate query refanout changed")
      for path in paths do
        unless path.leafData == expectedImage do
          throw (IO.userError "padded leaf image differs from explicit fixture")
        let occupied := path.leafData.drop (width-stored.length)
        unless occupied == stored && occupied.reverse == expectedFold do
          throw (IO.userError "occupied row trimming or single reversal is incorrect")
    let execution := DuplexModeGame.runReal DuplexModeGame.blake2sOracle DuplexCompression.parameterIV
      (WHIRPhysicalVerifier.openRows proof committed 1 [0,0] stored.length width true)
    unless execution.primitiveCost == (if width == 64 then 8 else 1) do
      throw (IO.userError "physical base verifier hid or duplicated a primitive call")
    match execution.view.result with
    | none => throw (IO.userError "counted physical base verifier rejected fixture")
    | some out =>
      unless out.rows == #[stored.toArray.map E.ofK,stored.toArray.map E.ofK] do
        throw (IO.userError "physical base decoder changed occupied lane order")
      unless Protocol.enforced out.rows (Array.replicate width.log2 0) #[1,0] true == E.ofK 7 do
        throw (IO.userError "actual base fold consumer did not reverse the occupied row exactly once")
  let extensionWords : List K := [1,2,3,4,5,6]
  let extensionRoot := PublicMerkleLog.hashBlake2s (ByteCodec.wordsBytes extensionWords)
  unless (List.ofFn extensionRoot).map Fin.val ==
      [0x3f,0xea,0x0b,0x3a,0x10,0x71,0x4c,0x40,0x9f,0x45,0xe2,0x01,0x9e,0xdf,0xd8,0x9f,
       0x72,0x49,0x8c,0x61,0xe8,0x45,0x55,0x94,0x52,0x55,0x1e,0x7c,0xec,0x1b,0xed,0xea] do
    throw (IO.userError "extension leaf differs from independent hashlib fixture")
  let extension := DuplexModeGame.runReal DuplexModeGame.blake2sOracle DuplexCompression.parameterIV
    (WHIRPhysicalVerifier.openRows ⟨[extensionWords],[]⟩ extensionRoot 1 [0,0] 6 6 false)
  unless extension.primitiveCost == 1 do throw (IO.userError "extension leaf compression was not counted once")
  match extension.view.result with
  | none => throw (IO.userError "physical extension decoder rejected a valid row")
  | some out =>
    let row : Array E := #[⟨1,2,3⟩,⟨4,5,6⟩]
    unless out.rows == #[row,row] do throw (IO.userError "extension limbs were reordered or reversed")
  IO.println "padded64/full4 base and E2 extension: independent BLAKE2s roots, actual counted physical verification, duplicate queries, single base reversal passed"

#eval smoke

end Whir.WHIRPhysicalRowsRegression
