// Generated by verification/circuits/GenerateRec.lean from LeanVMCircuits.Rec.Tables. Do not edit.
//! The recursion tables' slot forms and identities, proven in `LeanVMCircuits.Rec.Tables`.

use crate::leaf::Coord::{self, Col, Const, Prod, Sum};
use primitives::field::F64;

/// An identity: `(column, coefficient)` terms and `(column, column, coefficient)` products, coefficients as
/// `K` words, summing to zero.
pub(crate) type Identity = (&'static [(usize, u64)], &'static [(usize, usize, u64)]);

/// `EMUL`'s and `EXK`'s first factor.
pub(crate) const ARITH_A: usize = 0;
/// `EMUL`'s second factor, `EXK`'s `K` factor.
pub(crate) const ARITH_B: usize = 1;
/// `EMUL`'s and `EXK`'s addend.
pub(crate) const ARITH_D: usize = 2;
/// `EMUL`'s and `EXK`'s result.
pub(crate) const ARITH_C: usize = 3;
/// `HASH`'s chaining value.
pub(crate) const HASH_H: usize = 0;
/// `HASH`'s counter and finalization word.
pub(crate) const HASH_TF: usize = 1;
/// `HASH`'s mux (`Rec.node_row`).
pub(crate) const HASH_MUX: usize = 2;
/// `HASH`'s mux bit.
pub(crate) const HASH_SEL: usize = 3;
/// `HASH`'s message words four to six as an element.
pub(crate) const HASH_X: usize = 4;
/// `HASH`'s message word seven.
pub(crate) const HASH_DS: usize = 5;
/// `HASH`'s output.
pub(crate) const HASH_OUT: usize = 6;
/// `HASH`'s output's first three words as an element (`Rec.hash_outputs`).
pub(crate) const HASH_CH: usize = 7;
/// `HASH`'s first message word, the other seven after it.
pub(crate) const HASH_M: usize = 8;
/// `SPLIT`'s word.
pub(crate) const SPLIT_WORD: usize = 0;
/// `SPLIT`'s first bit, the other 63 after it.
pub(crate) const SPLIT_BITS: usize = 1;
/// `CAST`'s digest.
pub(crate) const CAST_DIGEST: usize = 0;
/// `CAST`'s element of the first three words.
pub(crate) const CAST_ELEMENT: usize = 1;
/// `CAST`'s low half, the high half after it.
pub(crate) const CAST_HALVES: usize = 2;
/// `CAST`'s first word, the other three after it.
pub(crate) const CAST_WORDS: usize = 4;

/// `EMUL`'s slot `s`: `a`, `b`, `d`, then `c = a·b + d` in `E` (`Rec.emul_spec`).
pub(crate) fn emul(s: usize) -> Option<[Coord; 4]> {
    Some(match s {
        0 => [Col(0), Col(1), Col(2), Const(F64(0x0))],
        1 => [Col(3), Col(4), Col(5), Const(F64(0x0))],
        2 => [Col(6), Col(7), Col(8), Const(F64(0x0))],
        3 => [
            Sum(vec![Prod(0, 3), Prod(1, 5), Prod(2, 4), Col(6)]),
            Sum(vec![Prod(0, 4), Prod(1, 3), Prod(1, 5), Prod(2, 4), Prod(2, 5), Col(7)]),
            Sum(vec![Prod(0, 5), Prod(1, 4), Prod(2, 3), Prod(2, 5), Col(8)]),
            Const(F64(0x0)),
        ],
        _ => return None,
    })
}

/// `EXK`'s slot `s`: `a`, `k`, `d`, then `c = a·k + d` (`Rec.exk_spec`).
pub(crate) fn exk(s: usize) -> Option<[Coord; 4]> {
    Some(match s {
        0 => [Col(0), Col(1), Col(2), Const(F64(0x0))],
        1 => [Col(3), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        2 => [Col(4), Col(5), Col(6), Const(F64(0x0))],
        3 => [
            Sum(vec![Prod(0, 3), Col(4)]),
            Sum(vec![Prod(1, 3), Col(5)]),
            Sum(vec![Prod(2, 3), Col(6)]),
            Const(F64(0x0)),
        ],
        _ => return None,
    })
}

/// `HASH`'s slot `s` over its ports and its mux bit (`Rec.hash_mux`).
pub(crate) fn hash(s: usize) -> Option<[Coord; 4]> {
    Some(match s {
        0 => [Col(2), Col(3), Col(4), Col(5)],
        1 => [Col(0), Col(1), Const(F64(0x0)), Const(F64(0x0))],
        2 => [
            Sum(vec![Col(6), Prod(18, 6), Prod(18, 10)]),
            Sum(vec![Col(7), Prod(18, 7), Prod(18, 11)]),
            Sum(vec![Col(8), Prod(18, 8), Prod(18, 12)]),
            Sum(vec![Col(9), Prod(18, 9), Prod(18, 13)]),
        ],
        3 => [Col(18), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        4 => [Col(10), Col(11), Col(12), Const(F64(0x0))],
        5 => [Col(13), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        6 => [Col(14), Col(15), Col(16), Col(17)],
        7 => [Col(14), Col(15), Col(16), Const(F64(0x0))],
        8 => [Col(6), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        9 => [Col(7), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        10 => [Col(8), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        11 => [Col(9), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        12 => [Col(10), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        13 => [Col(11), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        14 => [Col(12), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        15 => [Col(13), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        _ => return None,
    })
}

/// `SPLIT`'s slot `s`: the word, then its bits (`Rec.split_spec`).
pub(crate) const fn split(s: usize) -> Option<[Coord; 4]> {
    Some(match s {
        0 => [Col(0), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        1 => [Col(1), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        2 => [Col(2), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        3 => [Col(3), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        4 => [Col(4), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        5 => [Col(5), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        6 => [Col(6), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        7 => [Col(7), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        8 => [Col(8), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        9 => [Col(9), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        10 => [Col(10), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        11 => [Col(11), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        12 => [Col(12), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        13 => [Col(13), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        14 => [Col(14), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        15 => [Col(15), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        16 => [Col(16), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        17 => [Col(17), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        18 => [Col(18), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        19 => [Col(19), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        20 => [Col(20), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        21 => [Col(21), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        22 => [Col(22), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        23 => [Col(23), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        24 => [Col(24), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        25 => [Col(25), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        26 => [Col(26), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        27 => [Col(27), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        28 => [Col(28), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        29 => [Col(29), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        30 => [Col(30), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        31 => [Col(31), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        32 => [Col(32), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        33 => [Col(33), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        34 => [Col(34), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        35 => [Col(35), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        36 => [Col(36), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        37 => [Col(37), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        38 => [Col(38), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        39 => [Col(39), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        40 => [Col(40), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        41 => [Col(41), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        42 => [Col(42), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        43 => [Col(43), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        44 => [Col(44), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        45 => [Col(45), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        46 => [Col(46), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        47 => [Col(47), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        48 => [Col(48), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        49 => [Col(49), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        50 => [Col(50), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        51 => [Col(51), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        52 => [Col(52), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        53 => [Col(53), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        54 => [Col(54), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        55 => [Col(55), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        56 => [Col(56), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        57 => [Col(57), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        58 => [Col(58), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        59 => [Col(59), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        60 => [Col(60), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        61 => [Col(61), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        62 => [Col(62), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        63 => [Col(63), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        64 => [Col(64), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        _ => return None,
    })
}

/// `CAST`'s slot `s`: four words as a digest, an `E` element, two halves and four words.
pub(crate) const fn cast(s: usize) -> Option<[Coord; 4]> {
    Some(match s {
        0 => [Col(0), Col(1), Col(2), Col(3)],
        1 => [Col(0), Col(1), Col(2), Const(F64(0x0))],
        2 => [Col(0), Col(1), Const(F64(0x0)), Const(F64(0x0))],
        3 => [Col(2), Col(3), Const(F64(0x0)), Const(F64(0x0))],
        4 => [Col(0), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        5 => [Col(1), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        6 => [Col(2), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        7 => [Col(3), Const(F64(0x0)), Const(F64(0x0)), Const(F64(0x0))],
        _ => return None,
    })
}

/// `HASH`'s identities: its mux bit is Boolean (`Rec.hash_mux`).
pub(crate) const HASH_IDENTITIES: &[Identity] = &[(&[(18, 0x1)], &[(18, 18, 0x1)])];

/// `SPLIT`'s identities: the word is its bits' sum, each Boolean (`Rec.split_spec`).
pub(crate) const SPLIT_IDENTITIES: &[Identity] = &[
    (
        &[
            (0, 0x1),
            (1, 0x1),
            (2, 0x2),
            (3, 0x4),
            (4, 0x8),
            (5, 0x10),
            (6, 0x20),
            (7, 0x40),
            (8, 0x80),
            (9, 0x100),
            (10, 0x200),
            (11, 0x400),
            (12, 0x800),
            (13, 0x1000),
            (14, 0x2000),
            (15, 0x4000),
            (16, 0x8000),
            (17, 0x10000),
            (18, 0x20000),
            (19, 0x40000),
            (20, 0x80000),
            (21, 0x100000),
            (22, 0x200000),
            (23, 0x400000),
            (24, 0x800000),
            (25, 0x1000000),
            (26, 0x2000000),
            (27, 0x4000000),
            (28, 0x8000000),
            (29, 0x10000000),
            (30, 0x20000000),
            (31, 0x40000000),
            (32, 0x80000000),
            (33, 0x100000000),
            (34, 0x200000000),
            (35, 0x400000000),
            (36, 0x800000000),
            (37, 0x1000000000),
            (38, 0x2000000000),
            (39, 0x4000000000),
            (40, 0x8000000000),
            (41, 0x10000000000),
            (42, 0x20000000000),
            (43, 0x40000000000),
            (44, 0x80000000000),
            (45, 0x100000000000),
            (46, 0x200000000000),
            (47, 0x400000000000),
            (48, 0x800000000000),
            (49, 0x1000000000000),
            (50, 0x2000000000000),
            (51, 0x4000000000000),
            (52, 0x8000000000000),
            (53, 0x10000000000000),
            (54, 0x20000000000000),
            (55, 0x40000000000000),
            (56, 0x80000000000000),
            (57, 0x100000000000000),
            (58, 0x200000000000000),
            (59, 0x400000000000000),
            (60, 0x800000000000000),
            (61, 0x1000000000000000),
            (62, 0x2000000000000000),
            (63, 0x4000000000000000),
            (64, 0x8000000000000000),
        ],
        &[],
    ),
    (&[(1, 0x1)], &[(1, 1, 0x1)]),
    (&[(2, 0x1)], &[(2, 2, 0x1)]),
    (&[(3, 0x1)], &[(3, 3, 0x1)]),
    (&[(4, 0x1)], &[(4, 4, 0x1)]),
    (&[(5, 0x1)], &[(5, 5, 0x1)]),
    (&[(6, 0x1)], &[(6, 6, 0x1)]),
    (&[(7, 0x1)], &[(7, 7, 0x1)]),
    (&[(8, 0x1)], &[(8, 8, 0x1)]),
    (&[(9, 0x1)], &[(9, 9, 0x1)]),
    (&[(10, 0x1)], &[(10, 10, 0x1)]),
    (&[(11, 0x1)], &[(11, 11, 0x1)]),
    (&[(12, 0x1)], &[(12, 12, 0x1)]),
    (&[(13, 0x1)], &[(13, 13, 0x1)]),
    (&[(14, 0x1)], &[(14, 14, 0x1)]),
    (&[(15, 0x1)], &[(15, 15, 0x1)]),
    (&[(16, 0x1)], &[(16, 16, 0x1)]),
    (&[(17, 0x1)], &[(17, 17, 0x1)]),
    (&[(18, 0x1)], &[(18, 18, 0x1)]),
    (&[(19, 0x1)], &[(19, 19, 0x1)]),
    (&[(20, 0x1)], &[(20, 20, 0x1)]),
    (&[(21, 0x1)], &[(21, 21, 0x1)]),
    (&[(22, 0x1)], &[(22, 22, 0x1)]),
    (&[(23, 0x1)], &[(23, 23, 0x1)]),
    (&[(24, 0x1)], &[(24, 24, 0x1)]),
    (&[(25, 0x1)], &[(25, 25, 0x1)]),
    (&[(26, 0x1)], &[(26, 26, 0x1)]),
    (&[(27, 0x1)], &[(27, 27, 0x1)]),
    (&[(28, 0x1)], &[(28, 28, 0x1)]),
    (&[(29, 0x1)], &[(29, 29, 0x1)]),
    (&[(30, 0x1)], &[(30, 30, 0x1)]),
    (&[(31, 0x1)], &[(31, 31, 0x1)]),
    (&[(32, 0x1)], &[(32, 32, 0x1)]),
    (&[(33, 0x1)], &[(33, 33, 0x1)]),
    (&[(34, 0x1)], &[(34, 34, 0x1)]),
    (&[(35, 0x1)], &[(35, 35, 0x1)]),
    (&[(36, 0x1)], &[(36, 36, 0x1)]),
    (&[(37, 0x1)], &[(37, 37, 0x1)]),
    (&[(38, 0x1)], &[(38, 38, 0x1)]),
    (&[(39, 0x1)], &[(39, 39, 0x1)]),
    (&[(40, 0x1)], &[(40, 40, 0x1)]),
    (&[(41, 0x1)], &[(41, 41, 0x1)]),
    (&[(42, 0x1)], &[(42, 42, 0x1)]),
    (&[(43, 0x1)], &[(43, 43, 0x1)]),
    (&[(44, 0x1)], &[(44, 44, 0x1)]),
    (&[(45, 0x1)], &[(45, 45, 0x1)]),
    (&[(46, 0x1)], &[(46, 46, 0x1)]),
    (&[(47, 0x1)], &[(47, 47, 0x1)]),
    (&[(48, 0x1)], &[(48, 48, 0x1)]),
    (&[(49, 0x1)], &[(49, 49, 0x1)]),
    (&[(50, 0x1)], &[(50, 50, 0x1)]),
    (&[(51, 0x1)], &[(51, 51, 0x1)]),
    (&[(52, 0x1)], &[(52, 52, 0x1)]),
    (&[(53, 0x1)], &[(53, 53, 0x1)]),
    (&[(54, 0x1)], &[(54, 54, 0x1)]),
    (&[(55, 0x1)], &[(55, 55, 0x1)]),
    (&[(56, 0x1)], &[(56, 56, 0x1)]),
    (&[(57, 0x1)], &[(57, 57, 0x1)]),
    (&[(58, 0x1)], &[(58, 58, 0x1)]),
    (&[(59, 0x1)], &[(59, 59, 0x1)]),
    (&[(60, 0x1)], &[(60, 60, 0x1)]),
    (&[(61, 0x1)], &[(61, 61, 0x1)]),
    (&[(62, 0x1)], &[(62, 62, 0x1)]),
    (&[(63, 0x1)], &[(63, 63, 0x1)]),
    (&[(64, 0x1)], &[(64, 64, 0x1)]),
];

/// `(a, b, a·b)` in `K`, by the carry-less product proven to be `K`'s multiplication (`Rec.ev_mul`).
#[cfg(test)]
pub(crate) const K_PRODUCTS: &[(u64, u64, u64)] = &[
    (0x0, 0x0, 0x0),
    (0x0, 0x1, 0x0),
    (0x0, 0x2, 0x0),
    (0x0, 0x1b, 0x0),
    (0x0, 0x8000000000000000, 0x0),
    (0x0, 0xffffffffffffffff, 0x0),
    (0x0, 0x5c62236777028505, 0x0),
    (0x0, 0x53cad161bf5a89c7, 0x0),
    (0x0, 0x123456789abcdef, 0x0),
    (0x0, 0xfedcba9876543210, 0x0),
    (0x1, 0x0, 0x0),
    (0x1, 0x1, 0x1),
    (0x1, 0x2, 0x2),
    (0x1, 0x1b, 0x1b),
    (0x1, 0x8000000000000000, 0x8000000000000000),
    (0x1, 0xffffffffffffffff, 0xffffffffffffffff),
    (0x1, 0x5c62236777028505, 0x5c62236777028505),
    (0x1, 0x53cad161bf5a89c7, 0x53cad161bf5a89c7),
    (0x1, 0x123456789abcdef, 0x123456789abcdef),
    (0x1, 0xfedcba9876543210, 0xfedcba9876543210),
    (0x2, 0x0, 0x0),
    (0x2, 0x1, 0x2),
    (0x2, 0x2, 0x4),
    (0x2, 0x1b, 0x36),
    (0x2, 0x8000000000000000, 0x1b),
    (0x2, 0xffffffffffffffff, 0xffffffffffffffe5),
    (0x2, 0x5c62236777028505, 0xb8c446ceee050a0a),
    (0x2, 0x53cad161bf5a89c7, 0xa795a2c37eb5138e),
    (0x2, 0x123456789abcdef, 0x2468acf13579bde),
    (0x2, 0xfedcba9876543210, 0xfdb97530eca8643b),
    (0x1b, 0x0, 0x0),
    (0x1b, 0x1, 0x1b),
    (0x1b, 0x2, 0x36),
    (0x1b, 0x1b, 0x145),
    (0x1b, 0x8000000000000000, 0x80000000000000af),
    (0x1b, 0xffffffffffffffff, 0xca),
    (0x1b, 0x5c62236777028505, 0xc19548e5513bf736),
    (0x1b, 0x53cad161bf5a89c7, 0x56a4eeb4ce934840),
    (0x1b, 0x123456789abcdef, 0x184bb2ec4d1ee7b9),
    (0x1b, 0xfedcba9876543210, 0x184bb2ec4d1ee773),
    (0x8000000000000000, 0x0, 0x0),
    (0x8000000000000000, 0x1, 0x8000000000000000),
    (0x8000000000000000, 0x2, 0x1b),
    (0x8000000000000000, 0x1b, 0x80000000000000af),
    (0x8000000000000000, 0x8000000000000000, 0xc00000000000005a),
    (0x8000000000000000, 0xffffffffffffffff, 0x65),
    (0x8000000000000000, 0x5c62236777028505, 0x60caa472a89dfb9b),
    (0x8000000000000000, 0x53cad161bf5a89c7, 0x2b52775a6749a420),
    (0x8000000000000000, 0x123456789abcdef, 0x8c25d976268f73d1),
    (0x8000000000000000, 0xfedcba9876543210, 0x8c25d976268f73b4),
    (0xffffffffffffffff, 0x0, 0x0),
    (0xffffffffffffffff, 0x1, 0xffffffffffffffff),
    (0xffffffffffffffff, 0x2, 0xffffffffffffffe5),
    (0xffffffffffffffff, 0x1b, 0xca),
    (0xffffffffffffffff, 0x8000000000000000, 0x65),
    (0xffffffffffffffff, 0xffffffffffffffff, 0x5555555555555513),
    (0xffffffffffffffff, 0x5c62236777028505, 0x74ad2681e2172e11),
    (0xffffffffffffffff, 0x53cad161bf5a89c7, 0xfcda154cd0b8bf74),
    (0xffffffffffffffff, 0x123456789abcdef, 0x8d85286bc6ce632),
    (0xffffffffffffffff, 0xfedcba9876543210, 0x5d8d07d3e939b321),
    (0x5c62236777028505, 0x0, 0x0),
    (0x5c62236777028505, 0x1, 0x5c62236777028505),
    (0x5c62236777028505, 0x2, 0xb8c446ceee050a0a),
    (0x5c62236777028505, 0x1b, 0xc19548e5513bf736),
    (0x5c62236777028505, 0x8000000000000000, 0x60caa472a89dfb9b),
    (0x5c62236777028505, 0xffffffffffffffff, 0x74ad2681e2172e11),
    (0x5c62236777028505, 0x5c62236777028505, 0xb964dc682c67ddcd),
    (0x5c62236777028505, 0x53cad161bf5a89c7, 0xa795a2c37eb5138f),
    (0x5c62236777028505, 0x123456789abcdef, 0x160761e0f06b2448),
    (0x5c62236777028505, 0xfedcba9876543210, 0x62aa4761127c0a59),
    (0x53cad161bf5a89c7, 0x0, 0x0),
    (0x53cad161bf5a89c7, 0x1, 0x53cad161bf5a89c7),
    (0x53cad161bf5a89c7, 0x2, 0xa795a2c37eb5138e),
    (0x53cad161bf5a89c7, 0x1b, 0x56a4eeb4ce934840),
    (0x53cad161bf5a89c7, 0x8000000000000000, 0x2b52775a6749a420),
    (0x53cad161bf5a89c7, 0xffffffffffffffff, 0xfcda154cd0b8bf74),
    (0x53cad161bf5a89c7, 0x5c62236777028505, 0xa795a2c37eb5138f),
    (0x53cad161bf5a89c7, 0x53cad161bf5a89c7, 0xee2567ef2b5b8c15),
    (0x53cad161bf5a89c7, 0x123456789abcdef, 0x6483e0130ef2eb4),
    (0x53cad161bf5a89c7, 0xfedcba9876543210, 0xfa922b4de05791c0),
    (0x123456789abcdef, 0x0, 0x0),
    (0x123456789abcdef, 0x1, 0x123456789abcdef),
    (0x123456789abcdef, 0x2, 0x2468acf13579bde),
    (0x123456789abcdef, 0x1b, 0x184bb2ec4d1ee7b9),
    (0x123456789abcdef, 0x8000000000000000, 0x8c25d976268f73d1),
    (0x123456789abcdef, 0xffffffffffffffff, 0x8d85286bc6ce632),
    (0x123456789abcdef, 0x5c62236777028505, 0x160761e0f06b2448),
    (0x123456789abcdef, 0x53cad161bf5a89c7, 0x6483e0130ef2eb4),
    (0x123456789abcdef, 0x123456789abcdef, 0x405a2833e1fb8992),
    (0x123456789abcdef, 0xfedcba9876543210, 0x48827ab55d976fa0),
    (0xfedcba9876543210, 0x0, 0x0),
    (0xfedcba9876543210, 0x1, 0xfedcba9876543210),
    (0xfedcba9876543210, 0x2, 0xfdb97530eca8643b),
    (0xfedcba9876543210, 0x1b, 0x184bb2ec4d1ee773),
    (0xfedcba9876543210, 0x8000000000000000, 0x8c25d976268f73b4),
    (0xfedcba9876543210, 0xffffffffffffffff, 0x5d8d07d3e939b321),
    (0xfedcba9876543210, 0x5c62236777028505, 0x62aa4761127c0a59),
    (0xfedcba9876543210, 0x53cad161bf5a89c7, 0xfa922b4de05791c0),
    (0xfedcba9876543210, 0x123456789abcdef, 0x48827ab55d976fa0),
    (0xfedcba9876543210, 0xfedcba9876543210, 0x150f7d66b4aedc81),
];

/// `PARAM_IV` (`Rec.paramIV`).
#[cfg(test)]
pub(crate) const PARAM_IV_WORDS: [u64; 4] = [
    0xbb67ae856b08e647,
    0xa54ff53a3c6ef372,
    0x9b05688c510e527f,
    0x5be0cd191f83d9ab,
];

/// The chaining values after zero, one, two and three zero blocks (`Rec.absorb`).
#[cfg(test)]
pub(crate) const ZERO_PREFIXES: [[u64; 4]; 4] = [
    [
        0xbb67ae856b08e647,
        0xa54ff53a3c6ef372,
        0x9b05688c510e527f,
        0x5be0cd191f83d9ab,
    ],
    [
        0x395c719a76f2efc5,
        0x9c979482e7a2c3ab,
        0xb94f62da3d657ff1,
        0x74410f1aa68a7b7c,
    ],
    [
        0x307b6ba6f231de41,
        0x7136bd060d87a0d7,
        0x375ad72c9065164d,
        0x71e8fa9124d665b3,
    ],
    [
        0x274644cf1a7f7e2f,
        0xedb680d3d8a53d0f,
        0x767078dfbc4cb374,
        0x178449f05bf79829,
    ],
];

/// `SEED`, `OUTPUT`, `COMMIT`, `POW_BASE`, `NONCE` and `POW_TAG` (`Rec.seedTag` and the rest).
#[cfg(test)]
pub(crate) const DUPLEX_TAGS: [u64; 6] = [
    0x100000000000000,
    0x600000000000000,
    0x700000000000000,
    0x800000000000000,
    0x900000000000000,
    0x31574f502d534646,
];

/// `(first, last, len, previous, absorb_tweak(first, last, len, previous))` (`Rec.tweak`).
#[cfg(test)]
pub(crate) const ABSORB_TWEAKS: &[(bool, bool, usize, u64, u64)] = &[
    (true, true, 8, 0x0, 0x410000000000000),
    (true, true, 8, 0x18, 0x410000000000018),
    (true, true, 8, 0x1ffffffffffff, 0x411ffffffffffff),
    (true, true, 24, 0x0, 0x430000000000000),
    (true, true, 24, 0x18, 0x430000000000018),
    (true, true, 24, 0x1ffffffffffff, 0x431ffffffffffff),
    (true, true, 64, 0x0, 0x480000000000000),
    (true, true, 64, 0x18, 0x480000000000018),
    (true, true, 64, 0x1ffffffffffff, 0x481ffffffffffff),
    (true, false, 64, 0x0, 0x280000000000000),
    (true, false, 64, 0x18, 0x280000000000018),
    (true, false, 64, 0x1ffffffffffff, 0x281ffffffffffff),
    (false, true, 8, 0x0, 0x510000000000000),
    (false, true, 24, 0x0, 0x530000000000000),
    (false, true, 64, 0x0, 0x580000000000000),
    (false, false, 64, 0x0, 0x380000000000000),
];
