[package]
name = "falcon-host"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
falcon = { path = "../guest" }
leanvm_guest.workspace = true
parallel.workspace = true
tide-fn-dsa = "0.4"

[dev-dependencies]
leanvm.workspace = true
primitives.workspace = true
proptest.workspace = true
