-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [leanxmss]: function definitions
import Aeneas
import Leanxmss.Types
import Leanxmss.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace leanxmss

/-- Trait implementation: [leanvm_guest::plain::{impl leanvm_guest::plain::Plain for u32}]
    Source: 'sdk/src/lib.rs', lines 40:4-40:22
    Name pattern: [leanvm_guest::plain::Plain<u32>] -/
@[reducible, rust_trait_impl "leanvm_guest::plain::Plain<u32>"]
def U32.Insts.Leanvm_guestPlainPlain : leanvm_guest.plain.Plain Std.U32 := {
  SIZE := U32.Insts.Leanvm_guestPlainPlain.SIZE
  ALIGN := U32.Insts.Leanvm_guestPlainPlain.ALIGN
  coremarkerCopyInst := core.marker.CopyU32
  byte := U32.Insts.Leanvm_guestPlainPlain.byte
}

/-- Trait implementation: [leanvm_guest::plain::{impl leanvm_guest::plain::Plain for u64}]
    Source: 'sdk/src/lib.rs', lines 47:4-47:22
    Name pattern: [leanvm_guest::plain::Plain<u64>] -/
@[reducible, rust_trait_impl "leanvm_guest::plain::Plain<u64>"]
def U64.Insts.Leanvm_guestPlainPlain : leanvm_guest.plain.Plain Std.U64 := {
  SIZE := U64.Insts.Leanvm_guestPlainPlain.SIZE
  ALIGN := U64.Insts.Leanvm_guestPlainPlain.ALIGN
  coremarkerCopyInst := core.marker.CopyU64
  byte := U64.Insts.Leanvm_guestPlainPlain.byte
}

/-- Trait implementation: [leanvm_guest::plain::{impl leanvm_guest::plain::Plain for [T; N]}]
    Source: 'sdk/src/lib.rs', lines 54:4-54:51
    Name pattern: [leanvm_guest::plain::Plain<[@T; @N]>] -/
@[reducible, rust_trait_impl "leanvm_guest::plain::Plain<[@T; @N]>"]
def Array.Insts.Leanvm_guestPlainPlain {T : Type} (N : Std.Usize) (PlainInst :
  leanvm_guest.plain.Plain T) : leanvm_guest.plain.Plain (Array T N) := {
  SIZE := Array.Insts.Leanvm_guestPlainPlain.SIZE N PlainInst
  ALIGN := Array.Insts.Leanvm_guestPlainPlain.ALIGN N PlainInst
  coremarkerCopyInst := Array.Insts.CoreMarkerCopy N
    PlainInst.coremarkerCopyInst
  byte := Array.Insts.Leanvm_guestPlainPlain.byte PlainInst
}

/-- [leanxmss::V]
    Source: 'src/lib.rs', lines 42:0-42:24
    Visibility: public -/
@[global_simps, irreducible] def V : Std.Usize := 42#usize

/-- [leanxmss::W]
    Source: 'src/lib.rs', lines 44:0-44:23
    Visibility: public -/
@[global_simps, irreducible] def W : Std.Usize := 3#usize

/-- [leanxmss::CHAIN_LENGTH]
    Source: 'src/lib.rs', lines 46:0-46:39
    Visibility: public -/
@[global_simps, irreducible]
def CHAIN_LENGTH : Result Std.Usize := 1#usize <<< W

/-- [leanxmss::NUM_CHAIN_HASHES]
    Source: 'src/lib.rs', lines 48:0-48:39
    Visibility: public -/
@[global_simps, irreducible] def NUM_CHAIN_HASHES : Std.Usize := 99#usize

/-- [leanxmss::TARGET_SUM]
    Source: 'src/lib.rs', lines 52:0-52:72
    Visibility: public -/
@[global_simps, irreducible]
def TARGET_SUM : Result Std.Usize := do
  let i ← CHAIN_LENGTH
  let i1 ← i - 1#usize
  let i2 ← V * i1
  i2 - NUM_CHAIN_HASHES

/-- [leanxmss::PROTOCOL_DOMAIN_SEP]
    Source: 'src/lib.rs', lines 66:0-66:34 -/
@[global_simps, irreducible] def PROTOCOL_DOMAIN_SEP : Std.U8 := 0#u8

/-- [leanxmss::TWEAK_CHAIN]
    Source: 'src/lib.rs', lines 70:0-70:26 -/
@[global_simps, irreducible] def TWEAK_CHAIN : Std.U8 := 1#u8

/-- [leanxmss::TWEAK_WOTS_PK]
    Source: 'src/lib.rs', lines 71:0-71:28 -/
@[global_simps, irreducible] def TWEAK_WOTS_PK : Std.U8 := 2#u8

/-- [leanxmss::TWEAK_MERKLE]
    Source: 'src/lib.rs', lines 72:0-72:27 -/
@[global_simps, irreducible] def TWEAK_MERKLE : Std.U8 := 3#u8

/-- [leanxmss::TWEAK_ENCODING]
    Source: 'src/lib.rs', lines 73:0-73:29 -/
@[global_simps, irreducible] def TWEAK_ENCODING : Std.U8 := 4#u8

/-- [leanxmss::TWEAK_INDEX]
    Source: 'src/lib.rs', lines 286:0-286:30 -/
@[global_simps, irreducible] def TWEAK_INDEX : Std.Usize := 12#usize

/-- [leanxmss::TWEAK_POSITION]
    Source: 'src/lib.rs', lines 180:0-180:32 -/
@[global_simps, irreducible] def TWEAK_POSITION : Std.Usize := 4#usize

/-- [leanxmss::PAYLOAD]
    Source: 'src/lib.rs', lines 178:0-178:25 -/
@[global_simps, irreducible] def PAYLOAD : Std.Usize := 4#usize

/-- [leanxmss::digest]:
    Source: 'src/lib.rs', lines 173:0-175:1 -/
def digest (a : Array Std.U64 4#usize) : Result (Array Std.U64 2#usize) := do
  let d0 ← Array.index_usize a 0#usize
  let d1 ← Array.index_usize a 1#usize
  ok (Array.make 2#usize [ d0, d1 ])

/-- [leanxmss::merkle_node]:
    Source: 'src/lib.rs', lines 293:0-301:1 -/
def merkle_node
  (LEVEL : Std.Usize) (node : leanvm_guest.Template 8#usize) (bits : Std.U64)
  (child : Array Std.U64 2#usize) (sibling : Array Std.U64 2#usize) :
  Result ((Array Std.U64 2#usize) × (leanvm_guest.Template 8#usize))
  := do
  let i ← bits <<< 4#i32
  let i1 ← i >>> LEVEL
  let i2 ← lift (i1 &&& 16#u64)
  let side ← lift (UScalar.cast .Usize i2)
  let i3 ← LEVEL + 1#usize
  let i4 ← lift (UScalar.cast .U32 i3)
  let node1 ←
    leanvm_guest.Template.write U32.Insts.Leanvm_guestPlainPlain node
      TWEAK_POSITION i4
  let i5 ← bits >>> i3
  let i6 ← lift (UScalar.cast .U32 i5)
  let node2 ←
    leanvm_guest.Template.write U32.Insts.Leanvm_guestPlainPlain node1
      TWEAK_INDEX i6
  let i7 ← 8#usize * PAYLOAD
  let i8 ← i7 + side
  let node3 ←
    leanvm_guest.Template.write (Array.Insts.Leanvm_guestPlainPlain 2#usize
      U64.Insts.Leanvm_guestPlainPlain) node2 i8 child
  let i9 ← i7 + 16#usize
  let i10 ← i9 - side
  let node4 ←
    leanvm_guest.Template.write (Array.Insts.Leanvm_guestPlainPlain 2#usize
      U64.Insts.Leanvm_guestPlainPlain) node3 i10 sibling
  let (a, node5) ← leanvm_guest.Template.digest node4
  let a1 ← digest a
  ok (a1, node5)

/-- [leanxmss::tweak]:
    Source: 'src/lib.rs', lines 156:0-161:1 -/
def tweak
  (ty : Std.U8) (position : Std.U32) (index : Std.U32) :
  Result (Array Std.U64 2#usize)
  := do
  let i ← lift (core.convert.num.FromU64U8.from PROTOCOL_DOMAIN_SEP)
  let i1 ← lift (core.convert.num.FromU64U8.from ty)
  let i2 ← i1 <<< 8#i32
  let i3 ← lift (i ||| i2)
  let i4 ← lift (core.convert.num.FromU64U32.from position)
  let i5 ← i4 <<< 32#i32
  let i6 ← lift (i3 ||| i5)
  let i7 ← lift (core.convert.num.FromU64U32.from index)
  let i8 ← i7 <<< 32#i32
  ok (Array.make 2#usize [ i6, i8 ])

/-- [leanxmss::merkle_root]:
    Source: 'src/lib.rs', lines 273:0-283:1 -/
def merkle_root
  (pp : Array Std.U64 2#usize) (leaf_index : Std.U32)
  (leaf : Array Std.U64 2#usize)
  (path : Array (Array Std.U64 2#usize) 32#usize) :
  Result (Array Std.U64 2#usize)
  := do
  let a ← tweak TWEAK_MERKLE 0#u32 0#u32
  let t0 ← Array.index_usize a 0#usize
  let t1 ← Array.index_usize a 1#usize
  let i ← Array.index_usize pp 0#usize
  let i1 ← Array.index_usize pp 1#usize
  let node ←
    leanvm_guest.Template.new
      (Array.make 8#usize [ t0, t1, i, i1, 0#u64, 0#u64, 0#u64, 0#u64 ])
  let bits ← lift (core.convert.num.FromU64U32.from leaf_index)
  let a1 ← Array.index_usize path 0#usize
  let (child, node1) ← merkle_node 0#usize node bits leaf a1
  let a2 ← Array.index_usize path 1#usize
  let (child1, node2) ← merkle_node 1#usize node1 bits child a2
  let a3 ← Array.index_usize path 2#usize
  let (child2, node3) ← merkle_node 2#usize node2 bits child1 a3
  let a4 ← Array.index_usize path 3#usize
  let (child3, node4) ← merkle_node 3#usize node3 bits child2 a4
  let a5 ← Array.index_usize path 4#usize
  let (child4, node5) ← merkle_node 4#usize node4 bits child3 a5
  let a6 ← Array.index_usize path 5#usize
  let (child5, node6) ← merkle_node 5#usize node5 bits child4 a6
  let a7 ← Array.index_usize path 6#usize
  let (child6, node7) ← merkle_node 6#usize node6 bits child5 a7
  let a8 ← Array.index_usize path 7#usize
  let (child7, node8) ← merkle_node 7#usize node7 bits child6 a8
  let a9 ← Array.index_usize path 8#usize
  let (child8, node9) ← merkle_node 8#usize node8 bits child7 a9
  let a10 ← Array.index_usize path 9#usize
  let (child9, node10) ← merkle_node 9#usize node9 bits child8 a10
  let a11 ← Array.index_usize path 10#usize
  let (child10, node11) ← merkle_node 10#usize node10 bits child9 a11
  let a12 ← Array.index_usize path 11#usize
  let (child11, node12) ← merkle_node 11#usize node11 bits child10 a12
  let a13 ← Array.index_usize path 12#usize
  let (child12, node13) ← merkle_node 12#usize node12 bits child11 a13
  let a14 ← Array.index_usize path 13#usize
  let (child13, node14) ← merkle_node 13#usize node13 bits child12 a14
  let a15 ← Array.index_usize path 14#usize
  let (child14, node15) ← merkle_node 14#usize node14 bits child13 a15
  let a16 ← Array.index_usize path 15#usize
  let (child15, node16) ← merkle_node 15#usize node15 bits child14 a16
  let a17 ← Array.index_usize path 16#usize
  let (child16, node17) ← merkle_node 16#usize node16 bits child15 a17
  let a18 ← Array.index_usize path 17#usize
  let (child17, node18) ← merkle_node 17#usize node17 bits child16 a18
  let a19 ← Array.index_usize path 18#usize
  let (child18, node19) ← merkle_node 18#usize node18 bits child17 a19
  let a20 ← Array.index_usize path 19#usize
  let (child19, node20) ← merkle_node 19#usize node19 bits child18 a20
  let a21 ← Array.index_usize path 20#usize
  let (child20, node21) ← merkle_node 20#usize node20 bits child19 a21
  let a22 ← Array.index_usize path 21#usize
  let (child21, node22) ← merkle_node 21#usize node21 bits child20 a22
  let a23 ← Array.index_usize path 22#usize
  let (child22, node23) ← merkle_node 22#usize node22 bits child21 a23
  let a24 ← Array.index_usize path 23#usize
  let (child23, node24) ← merkle_node 23#usize node23 bits child22 a24
  let a25 ← Array.index_usize path 24#usize
  let (child24, node25) ← merkle_node 24#usize node24 bits child23 a25
  let a26 ← Array.index_usize path 25#usize
  let (child25, node26) ← merkle_node 25#usize node25 bits child24 a26
  let a27 ← Array.index_usize path 26#usize
  let (child26, node27) ← merkle_node 26#usize node26 bits child25 a27
  let a28 ← Array.index_usize path 27#usize
  let (child27, node28) ← merkle_node 27#usize node27 bits child26 a28
  let a29 ← Array.index_usize path 28#usize
  let (child28, node29) ← merkle_node 28#usize node28 bits child27 a29
  let a30 ← Array.index_usize path 29#usize
  let (child29, node30) ← merkle_node 29#usize node29 bits child28 a30
  let a31 ← Array.index_usize path 30#usize
  let (child30, node31) ← merkle_node 30#usize node30 bits child29 a31
  let a32 ← Array.index_usize path 31#usize
  let (child31, _) ← merkle_node 31#usize node31 bits child30 a32
  ok child31

/-- [leanxmss::wots_leaf::{impl core::ops::function::FnOnce<(&'_3 mut leanvm_guest::Stream,), ()> for leanxmss::wots_leaf::{closure}<'_0, '_1, '_2, T0>}::call_once]:
    Source: 'src/lib.rs', lines 260:21-266:5 -/
def wots_leaf.closure.Insts.CoreOpsFunctionFnOnceTupleMut3StreamTuple.call_once
  {T0 : Type} (coreopsfunctionFnMutT0TupleUsizeArrayU642Inst :
  core.ops.function.FnMut T0 Std.Usize (Array Std.U64 2#usize))
  (c : wots_leaf.closure T0) (tupled_args : leanvm_guest.Stream) :
  Result ((wots_leaf.closure T0) × leanvm_guest.Stream)
  := do
  let (i, a, t) := c
  let a1 ← tweak TWEAK_WOTS_PK 0#u32 i
  let (s, write_back) ← leanvm_guest.Stream.write tupled_args a1
  let (s1, write_back1) ← leanvm_guest.Stream.write s a
  let s2 := write_back1 s1
  let tupled_args1 := write_back s2
  let (a2, t1) ←
    coreopsfunctionFnMutT0TupleUsizeArrayU642Inst.call_mut t 0#usize
  let (s3, write_back2) ← leanvm_guest.Stream.write tupled_args1 a2
  let tupled_args2 := write_back2 s3
  let (a3, t2) ←
    coreopsfunctionFnMutT0TupleUsizeArrayU642Inst.call_mut t1 1#usize
  let (s4, write_back3) ← leanvm_guest.Stream.write tupled_args2 a3
  let tupled_args3 := write_back3 s4
  let (a4, t3) ←
    coreopsfunctionFnMutT0TupleUsizeArrayU642Inst.call_mut t2 2#usize
  let (s5, write_back4) ← leanvm_guest.Stream.write tupled_args3 a4
  let tupled_args4 := write_back4 s5
  let (a5, t4) ←
    coreopsfunctionFnMutT0TupleUsizeArrayU642Inst.call_mut t3 3#usize
  let (s6, write_back5) ← leanvm_guest.Stream.write tupled_args4 a5
  let tupled_args5 := write_back5 s6
  let (a6, t5) ←
    coreopsfunctionFnMutT0TupleUsizeArrayU642Inst.call_mut t4 4#usize
  let (s7, write_back6) ← leanvm_guest.Stream.write tupled_args5 a6
  let tupled_args6 := write_back6 s7
  let (a7, t6) ←
    coreopsfunctionFnMutT0TupleUsizeArrayU642Inst.call_mut t5 5#usize
  let (s8, write_back7) ← leanvm_guest.Stream.write tupled_args6 a7
  let tupled_args7 := write_back7 s8
  let (a8, t7) ←
    coreopsfunctionFnMutT0TupleUsizeArrayU642Inst.call_mut t6 6#usize
  let (s9, write_back8) ← leanvm_guest.Stream.write tupled_args7 a8
  let tupled_args8 := write_back8 s9
  let (a9, t8) ←
    coreopsfunctionFnMutT0TupleUsizeArrayU642Inst.call_mut t7 7#usize
  let (s10, write_back9) ← leanvm_guest.Stream.write tupled_args8 a9
  let tupled_args9 := write_back9 s10
  let (a10, t9) ←
    coreopsfunctionFnMutT0TupleUsizeArrayU642Inst.call_mut t8 8#usize
  let (s11, write_back10) ← leanvm_guest.Stream.write tupled_args9 a10
  let tupled_args10 := write_back10 s11
  let (a11, t10) ←
    coreopsfunctionFnMutT0TupleUsizeArrayU642Inst.call_mut t9 9#usize
  let (s12, write_back11) ← leanvm_guest.Stream.write tupled_args10 a11
  let tupled_args11 := write_back11 s12
  let (a12, t11) ←
    coreopsfunctionFnMutT0TupleUsizeArrayU642Inst.call_mut t10 10#usize
  let (s13, write_back12) ← leanvm_guest.Stream.write tupled_args11 a12
  let tupled_args12 := write_back12 s13
  let (a13, t12) ←
    coreopsfunctionFnMutT0TupleUsizeArrayU642Inst.call_mut t11 11#usize
  let (s14, write_back13) ← leanvm_guest.Stream.write tupled_args12 a13
  let tupled_args13 := write_back13 s14
  let (a14, t13) ←
    coreopsfunctionFnMutT0TupleUsizeArrayU642Inst.call_mut t12 12#usize
  let (s15, write_back14) ← leanvm_guest.Stream.write tupled_args13 a14
  let tupled_args14 := write_back14 s15
  let (a15, t14) ←
    coreopsfunctionFnMutT0TupleUsizeArrayU642Inst.call_mut t13 13#usize
  let (s16, write_back15) ← leanvm_guest.Stream.write tupled_args14 a15
  let tupled_args15 := write_back15 s16
  let (a16, t15) ←
    coreopsfunctionFnMutT0TupleUsizeArrayU642Inst.call_mut t14 14#usize
  let (s17, write_back16) ← leanvm_guest.Stream.write tupled_args15 a16
  let tupled_args16 := write_back16 s17
  let (a17, t16) ←
    coreopsfunctionFnMutT0TupleUsizeArrayU642Inst.call_mut t15 15#usize
  let (s18, write_back17) ← leanvm_guest.Stream.write tupled_args16 a17
  let tupled_args17 := write_back17 s18
  let (a18, t17) ←
    coreopsfunctionFnMutT0TupleUsizeArrayU642Inst.call_mut t16 16#usize
  let (s19, write_back18) ← leanvm_guest.Stream.write tupled_args17 a18
  let tupled_args18 := write_back18 s19
  let (a19, t18) ←
    coreopsfunctionFnMutT0TupleUsizeArrayU642Inst.call_mut t17 17#usize
  let (s20, write_back19) ← leanvm_guest.Stream.write tupled_args18 a19
  let tupled_args19 := write_back19 s20
  let (a20, t19) ←
    coreopsfunctionFnMutT0TupleUsizeArrayU642Inst.call_mut t18 18#usize
  let (s21, write_back20) ← leanvm_guest.Stream.write tupled_args19 a20
  let tupled_args20 := write_back20 s21
  let (a21, t20) ←
    coreopsfunctionFnMutT0TupleUsizeArrayU642Inst.call_mut t19 19#usize
  let (s22, write_back21) ← leanvm_guest.Stream.write tupled_args20 a21
  let tupled_args21 := write_back21 s22
  let (a22, t21) ←
    coreopsfunctionFnMutT0TupleUsizeArrayU642Inst.call_mut t20 20#usize
  let (s23, write_back22) ← leanvm_guest.Stream.write tupled_args21 a22
  let tupled_args22 := write_back22 s23
  let (a23, t22) ←
    coreopsfunctionFnMutT0TupleUsizeArrayU642Inst.call_mut t21 21#usize
  let (s24, write_back23) ← leanvm_guest.Stream.write tupled_args22 a23
  let tupled_args23 := write_back23 s24
  let (a24, t23) ←
    coreopsfunctionFnMutT0TupleUsizeArrayU642Inst.call_mut t22 22#usize
  let (s25, write_back24) ← leanvm_guest.Stream.write tupled_args23 a24
  let tupled_args24 := write_back24 s25
  let (a25, t24) ←
    coreopsfunctionFnMutT0TupleUsizeArrayU642Inst.call_mut t23 23#usize
  let (s26, write_back25) ← leanvm_guest.Stream.write tupled_args24 a25
  let tupled_args25 := write_back25 s26
  let (a26, t25) ←
    coreopsfunctionFnMutT0TupleUsizeArrayU642Inst.call_mut t24 24#usize
  let (s27, write_back26) ← leanvm_guest.Stream.write tupled_args25 a26
  let tupled_args26 := write_back26 s27
  let (a27, t26) ←
    coreopsfunctionFnMutT0TupleUsizeArrayU642Inst.call_mut t25 25#usize
  let (s28, write_back27) ← leanvm_guest.Stream.write tupled_args26 a27
  let tupled_args27 := write_back27 s28
  let (a28, t27) ←
    coreopsfunctionFnMutT0TupleUsizeArrayU642Inst.call_mut t26 26#usize
  let (s29, write_back28) ← leanvm_guest.Stream.write tupled_args27 a28
  let tupled_args28 := write_back28 s29
  let (a29, t28) ←
    coreopsfunctionFnMutT0TupleUsizeArrayU642Inst.call_mut t27 27#usize
  let (s30, write_back29) ← leanvm_guest.Stream.write tupled_args28 a29
  let tupled_args29 := write_back29 s30
  let (a30, t29) ←
    coreopsfunctionFnMutT0TupleUsizeArrayU642Inst.call_mut t28 28#usize
  let (s31, write_back30) ← leanvm_guest.Stream.write tupled_args29 a30
  let tupled_args30 := write_back30 s31
  let (a31, t30) ←
    coreopsfunctionFnMutT0TupleUsizeArrayU642Inst.call_mut t29 29#usize
  let (s32, write_back31) ← leanvm_guest.Stream.write tupled_args30 a31
  let tupled_args31 := write_back31 s32
  let (a32, t31) ←
    coreopsfunctionFnMutT0TupleUsizeArrayU642Inst.call_mut t30 30#usize
  let (s33, write_back32) ← leanvm_guest.Stream.write tupled_args31 a32
  let tupled_args32 := write_back32 s33
  let (a33, t32) ←
    coreopsfunctionFnMutT0TupleUsizeArrayU642Inst.call_mut t31 31#usize
  let (s34, write_back33) ← leanvm_guest.Stream.write tupled_args32 a33
  let tupled_args33 := write_back33 s34
  let (a34, t33) ←
    coreopsfunctionFnMutT0TupleUsizeArrayU642Inst.call_mut t32 32#usize
  let (s35, write_back34) ← leanvm_guest.Stream.write tupled_args33 a34
  let tupled_args34 := write_back34 s35
  let (a35, t34) ←
    coreopsfunctionFnMutT0TupleUsizeArrayU642Inst.call_mut t33 33#usize
  let (s36, write_back35) ← leanvm_guest.Stream.write tupled_args34 a35
  let tupled_args35 := write_back35 s36
  let (a36, t35) ←
    coreopsfunctionFnMutT0TupleUsizeArrayU642Inst.call_mut t34 34#usize
  let (s37, write_back36) ← leanvm_guest.Stream.write tupled_args35 a36
  let tupled_args36 := write_back36 s37
  let (a37, t36) ←
    coreopsfunctionFnMutT0TupleUsizeArrayU642Inst.call_mut t35 35#usize
  let (s38, write_back37) ← leanvm_guest.Stream.write tupled_args36 a37
  let tupled_args37 := write_back37 s38
  let (a38, t37) ←
    coreopsfunctionFnMutT0TupleUsizeArrayU642Inst.call_mut t36 36#usize
  let (s39, write_back38) ← leanvm_guest.Stream.write tupled_args37 a38
  let tupled_args38 := write_back38 s39
  let (a39, t38) ←
    coreopsfunctionFnMutT0TupleUsizeArrayU642Inst.call_mut t37 37#usize
  let (s40, write_back39) ← leanvm_guest.Stream.write tupled_args38 a39
  let tupled_args39 := write_back39 s40
  let (a40, t39) ←
    coreopsfunctionFnMutT0TupleUsizeArrayU642Inst.call_mut t38 38#usize
  let (s41, write_back40) ← leanvm_guest.Stream.write tupled_args39 a40
  let tupled_args40 := write_back40 s41
  let (a41, t40) ←
    coreopsfunctionFnMutT0TupleUsizeArrayU642Inst.call_mut t39 39#usize
  let (s42, write_back41) ← leanvm_guest.Stream.write tupled_args40 a41
  let tupled_args41 := write_back41 s42
  let (a42, t41) ←
    coreopsfunctionFnMutT0TupleUsizeArrayU642Inst.call_mut t40 40#usize
  let (s43, write_back42) ← leanvm_guest.Stream.write tupled_args41 a42
  let tupled_args42 := write_back42 s43
  let (a43, t42) ←
    coreopsfunctionFnMutT0TupleUsizeArrayU642Inst.call_mut t41 41#usize
  let (s44, write_back43) ← leanvm_guest.Stream.write tupled_args42 a43
  let tupled_args43 := write_back43 s44
  ok ((i, a, t42), tupled_args43)

/-- Trait implementation: [leanxmss::wots_leaf::{impl core::ops::function::FnOnce<(&'_3 mut leanvm_guest::Stream,), ()> for leanxmss::wots_leaf::{closure}<'_0, '_1, '_2, T0>}]
    Source: 'src/lib.rs', lines 260:21-266:5 -/
@[reducible]
def wots_leaf.closure.Insts.CoreOpsFunctionFnOnceTupleMut3StreamTuple {T0 :
  Type} (coreopsfunctionFnMutT0TupleUsizeArrayU642Inst :
  core.ops.function.FnMut T0 Std.Usize (Array Std.U64 2#usize)) :
  core.ops.function.FnOnce (wots_leaf.closure T0)
  leanvm_guest.Stream ((wots_leaf.closure T0) × leanvm_guest.Stream) := {
  call_once :=
    wots_leaf.closure.Insts.CoreOpsFunctionFnOnceTupleMut3StreamTuple.call_once
    coreopsfunctionFnMutT0TupleUsizeArrayU642Inst
}

/-- [leanxmss::wots_leaf]:
    Source: 'src/lib.rs', lines 258:0-267:1 -/
def wots_leaf
  {T0 : Type} (coreopsfunctionFnMutT0TupleUsizeArrayU642Inst :
  core.ops.function.FnMut T0 Std.Usize (Array Std.U64 2#usize))
  (pp : Array Std.U64 2#usize) (leaf_index : Std.U32) («end» : T0) :
  Result (Array Std.U64 2#usize)
  := do
  massert (V = 42#usize)
  let (a, _) ←
    leanvm_guest.hash_with
      (wots_leaf.closure.Insts.CoreOpsFunctionFnOnceTupleMut3StreamTuple
      coreopsfunctionFnMutT0TupleUsizeArrayU642Inst) (leaf_index, pp, «end»)
  digest a

/-- [leanxmss::{leanxmss::Chains}::new]:
    Source: 'src/lib.rs', lines 235:4-240:5 -/
def Chains.new
  (pp : Array Std.U64 2#usize) (leaf_index : Std.U32) : Result Chains := do
  let a ← tweak TWEAK_CHAIN 0#u32 leaf_index
  let t0 ← Array.index_usize a 0#usize
  let t1 ← Array.index_usize a 1#usize
  let i ← Array.index_usize pp 0#usize
  let i1 ← Array.index_usize pp 1#usize
  let t ←
    leanvm_guest.Template.new
      (Array.make 6#usize [ t0, t1, i, i1, 0#u64, 0#u64 ])
  ok { step := t }

/-- [leanxmss::{leanxmss::Digits}::sum::LOW6]
    Source: 'src/lib.rs', lines 201:8-201:48 -/
@[global_simps, irreducible]
def Digits.sum.LOW6 : Std.U64 := 17311559823019733055#u64

/-- [leanxmss::{leanxmss::Digits}::sum::EVEN]
    Source: 'src/lib.rs', lines 199:8-199:48 -/
@[global_simps, irreducible]
def Digits.sum.EVEN : Std.U64 := 8198552921648689607#u64

/-- [leanxmss::{leanxmss::Digits}::sum]:
    Source: 'src/lib.rs', lines 196:4-210:5 -/
def Digits.sum (self : Digits) : Result Std.U64 := do
  let low ← Array.index_usize self 0#usize
  let high ← Array.index_usize self 1#usize
  let i ← lift (low &&& Digits.sum.EVEN)
  let i1 ← low >>> W
  let i2 ← lift (i1 &&& Digits.sum.EVEN)
  let i3 ← i + i2
  let i4 ← lift (high &&& Digits.sum.EVEN)
  let i5 ← i3 + i4
  let i6 ← high >>> W
  let i7 ← lift (i6 &&& Digits.sum.EVEN)
  let s ← i5 + i7
  let i8 ← lift (s &&& Digits.sum.LOW6)
  let i9 ← s >>> 6#i32
  let i10 ← lift (i9 &&& Digits.sum.LOW6)
  let s1 ← i8 + i10
  let i11 ← s1 >>> 12#i32
  let s2 ← s1 + i11
  let i12 ← s2 >>> 24#i32
  let s3 ← s2 + i12
  let i13 ← s3 >>> 48#i32
  let i14 ← s3 + i13
  ok (i14 &&& 4095#u64)

/-- [leanxmss::tweak_hash::{impl core::ops::function::FnOnce<(&'_5 mut leanvm_guest::Stream,), ()> for leanxmss::tweak_hash::{closure}<'_0, '_1, '_2, '_3, '_4, N>}::call_once]:
    Source: 'src/lib.rs', lines 166:21-168:5 -/
def
  tweak_hash.closure.Insts.CoreOpsFunctionFnOnceTupleMut5StreamTuple.call_once
  {N : Std.Usize} (c : tweak_hash.closure N)
  (tupled_args : leanvm_guest.Stream) :
  Result leanvm_guest.Stream
  := do
  let (i, i1, i2, a, a1) := c
  let a2 ← tweak i i1 i2
  let (s, write_back) ← leanvm_guest.Stream.write tupled_args a2
  let (s1, write_back1) ← leanvm_guest.Stream.write s a
  let (s2, write_back2) ← leanvm_guest.Stream.write s1 a1
  let s3 := write_back2 s2
  let s4 := write_back1 s3
  ok (write_back s4)

/-- Trait implementation: [leanxmss::tweak_hash::{impl core::ops::function::FnOnce<(&'_5 mut leanvm_guest::Stream,), ()> for leanxmss::tweak_hash::{closure}<'_0, '_1, '_2, '_3, '_4, N>}]
    Source: 'src/lib.rs', lines 166:21-168:5 -/
@[reducible]
def tweak_hash.closure.Insts.CoreOpsFunctionFnOnceTupleMut5StreamTuple (N :
  Std.Usize) : core.ops.function.FnOnce (tweak_hash.closure N)
  leanvm_guest.Stream leanvm_guest.Stream := {
  call_once :=
    tweak_hash.closure.Insts.CoreOpsFunctionFnOnceTupleMut5StreamTuple.call_once
}

/-- [leanxmss::tweak_hash]:
    Source: 'src/lib.rs', lines 165:0-169:1 -/
def tweak_hash
  {N : Std.Usize} (pp : Array Std.U64 2#usize) (ty : Std.U8)
  (position : Std.U32) (index : Std.U32) (payload : Array Std.U64 N) :
  Result (Array Std.U64 2#usize)
  := do
  let a ←
    leanvm_guest.hash_with
      (tweak_hash.closure.Insts.CoreOpsFunctionFnOnceTupleMut5StreamTuple N)
      (ty, position, index, pp, payload)
  digest a

/-- [leanxmss::encode]:
    Source: 'src/lib.rs', lines 216:0-227:1 -/
def encode
  (pp : Array Std.U64 2#usize) (leaf_index : Std.U32)
  (message : Array Std.U64 4#usize) (randomness : Array Std.U64 3#usize) :
  Result (Option Digits)
  := do
  let m0 ← Array.index_usize message 0#usize
  let m1 ← Array.index_usize message 1#usize
  let m2 ← Array.index_usize message 2#usize
  let m3 ← Array.index_usize message 3#usize
  let r0 ← Array.index_usize randomness 0#usize
  let r1 ← Array.index_usize randomness 1#usize
  let r2 ← Array.index_usize randomness 2#usize
  let a ←
    tweak_hash pp TWEAK_ENCODING 0#u32 leaf_index
      (Array.make 8#usize [ m0, m1, m2, m3, r0, r1, r2, 0#u64 ])
  let low ← Array.index_usize a 0#usize
  let high ← Array.index_usize a 1#usize
  let i ← lift (low ||| high)
  let i1 ← W * V
  let i2 ← i1 / 2#usize
  let i3 ← i >>> i2
  if i3 != 0#u64
  then ok none
  else
    let i4 ← Digits.sum (Array.make 2#usize [ low, high ])
    let i5 ← TARGET_SUM
    let i6 ← lift (UScalar.cast .U64 i5)
    core.bool.Bool.then_some (i4 = i6) (Array.make 2#usize [ low, high ] :
      Array Std.U64 2#usize)

/-- [leanxmss::{leanxmss::Chains}::walk]:
    Source: 'src/lib.rs', lines 247:4-251:5 -/
def Chains.walk
  (self : Chains) (i : Std.Usize) (values : core.ops.range.Range Std.Usize)
  (value : Array Std.U64 2#usize) :
  Result ((Array Std.U64 2#usize) × Chains)
  := do
  let i1 ← CHAIN_LENGTH
  let i2 ← i * i1
  let first ← lift (UScalar.cast .U32 i2)
  let i3 ← lift (UScalar.cast .U32 values.start)
  let i4 ← first + i3
  let i5 ← lift (UScalar.cast .U32 values.end)
  let i6 ← first + i5
  let (a, t) ←
    leanvm_guest.Template.chain 4#usize 32#usize self.step
      { start := i4, «end» := i6 } value
  ok (a, { step := t })

/-- [leanxmss::{leanxmss::Digits}::get]:
    Source: 'src/lib.rs', lines 189:4-191:5 -/
def Digits.get (self : Digits) (i : Std.Usize) : Result Std.Usize := do
  let i1 ← V / 2#usize
  let i2 ← i / i1
  let i3 ← Array.index_usize self i2
  let i4 ← i % i1
  let i5 ← W * i4
  let i6 ← i3 >>> i5
  let i7 ← lift (UScalar.cast .Usize i6)
  let i8 ← CHAIN_LENGTH
  let i9 ← i8 - 1#usize
  ok (i7 &&& i9)

/-- [leanxmss::verify::{impl core::ops::function::FnMut<(usize,), [u64; 2usize]> for leanxmss::verify::{closure}<'_0, '_1, '_2>}::call_mut]:
    Source: 'src/lib.rs', lines 136:41-138:5 -/
def verify.closure.Insts.CoreOpsFunctionFnMutTupleUsizeArrayU642.call_mut
  (c : verify.closure) (tupled_args : Std.Usize) :
  Result ((Array Std.U64 2#usize) × verify.closure × (verify.closure →
    verify.closure))
  := do
  let (c1, d, s) := c
  let i ← Digits.get d tupled_args
  let i1 ← CHAIN_LENGTH
  let i2 ← i1 - 1#usize
  let a ← Array.index_usize s.chain_tips tupled_args
  let (a1, c2) ← Chains.walk c1 tupled_args { start := i, «end» := i2 } a
  let back := fun c3 => let (c4, _, _) := c3
                        (c4, d, s)
  ok (a1, (c2, d, s), back)

/-- [leanxmss::verify::{impl core::ops::function::FnOnce<(usize,), [u64; 2usize]> for leanxmss::verify::{closure}<'_0, '_1, '_2>}::call_once]:
    Source: 'src/lib.rs', lines 136:41-138:5 -/
def verify.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeArrayU642.call_once
  (c : verify.closure) (i : Std.Usize) :
  Result ((Array Std.U64 2#usize) × verify.closure)
  := do
  let (_, d, s) := c
  let (a, c1, call_mut_back) ←
    verify.closure.Insts.CoreOpsFunctionFnMutTupleUsizeArrayU642.call_mut c i
  let (c2, _, _) := call_mut_back c1
  ok (a, (c2, d, s))

/-- Trait implementation: [leanxmss::verify::{impl core::ops::function::FnOnce<(usize,), [u64; 2usize]> for leanxmss::verify::{closure}<'_0, '_1, '_2>}]
    Source: 'src/lib.rs', lines 136:41-138:5 -/
@[reducible]
def verify.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeArrayU642 :
  core.ops.function.FnOnce verify.closure Std.Usize (Array Std.U64 2#usize)
  := {
  call_once := fun c i => do
    let (a, _) ← verify.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeArrayU642.call_once c i
    ok a
}

/-- Trait implementation: [leanxmss::verify::{impl core::ops::function::FnMut<(usize,), [u64; 2usize]> for leanxmss::verify::{closure}<'_0, '_1, '_2>}]
    Source: 'src/lib.rs', lines 136:41-138:5 -/
@[reducible]
def verify.closure.Insts.CoreOpsFunctionFnMutTupleUsizeArrayU642 :
  core.ops.function.FnMut verify.closure Std.Usize (Array Std.U64 2#usize) := {
  FnOnceInst := verify.closure.Insts.CoreOpsFunctionFnOnceTupleUsizeArrayU642
  call_mut := fun c i => do
    let (a, c1, back) ← verify.closure.Insts.CoreOpsFunctionFnMutTupleUsizeArrayU642.call_mut c i
    ok (a, back c1)
}

/-- [leanxmss::verify]:
    Source: 'src/lib.rs', lines 124:0-146:1
    Visibility: public -/
def verify
  (pk : PublicKey) (leaf_index : Std.U32) (message : Array Std.U64 4#usize)
  (signature : Signature) :
  Result (core.result.Result Unit XmssVerifyError)
  := do
  let o ← encode pk.public_param leaf_index message signature.randomness
  let r ← core.option.Option.ok_or o XmssVerifyError.InvalidEncoding
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let chains ← Chains.new pk.public_param leaf_index
    let leaf ←
      wots_leaf verify.closure.Insts.CoreOpsFunctionFnMutTupleUsizeArrayU642
        pk.public_param leaf_index (chains, val, signature)
    let root ←
      merkle_root pk.public_param leaf_index leaf signature.merkle_proof
    let b ←
      core.array.equality.PartialEqArray.eq core.cmp.PartialEqU64 root
        pk.merkle_root
    if b
    then ok (core.result.Result.Ok ())
    else ok (core.result.Result.Err XmssVerifyError.InvalidMerklePath)
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTry_traitFromResidualResult.from_residual
      Unit (core.convert.FromSame XmssVerifyError) residual

end leanxmss
