-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [leanxmss]: type definitions
import Aeneas
import Leanxmss.TypesExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace leanxmss

/-- Trait declaration: [leanvm_guest::plain::Plain]
    Source: 'sdk/src/lib.rs', lines 17:4-17:25
    Name pattern: [leanvm_guest::plain::Plain]
    Visibility: public -/
@[rust_trait "leanvm_guest::plain::Plain"
  (parentClauses := ["coremarkerCopyInst"]) (consts := ["SIZE", "ALIGN"])]
structure leanvm_guest.plain.Plain (Self : Type) where
  SIZE : Result Std.Usize
  ALIGN : Result Std.Usize
  coremarkerCopyInst : core.marker.Copy Self
  byte : Self → Std.Usize → Result Std.U8

/-- [leanxmss::PublicKey]
    Source: 'src/lib.rs', lines 83:0-88:1
    Visibility: public -/
structure PublicKey where
  merkle_root : Array Std.U64 2#usize
  public_param : Array Std.U64 2#usize

/-- [leanxmss::Signature]
    Source: 'src/lib.rs', lines 95:0-102:1
    Visibility: public -/
structure Signature where
  chain_tips : Array (Array Std.U64 2#usize) 42#usize
  randomness : Array Std.U64 3#usize
  merkle_proof : Array (Array Std.U64 2#usize) 32#usize

/-- [leanxmss::XmssVerifyError]
    Source: 'src/lib.rs', lines 106:0-113:1
    Visibility: public -/
@[discriminant isize]
inductive XmssVerifyError where
| InvalidEncoding : XmssVerifyError
| InvalidMerklePath : XmssVerifyError

/-- [leanxmss::wots_leaf::{closure}]
    Source: 'src/lib.rs', lines 260:21-266:5 -/
def wots_leaf.closure (T0 : Type) := Std.U32 × Array Std.U64 2#usize × T0

/-- [leanxmss::Chains]
    Source: 'src/lib.rs', lines 230:0-232:1 -/
structure Chains where
  step : leanvm_guest.Template 6#usize

/-- [leanxmss::Digits]
    Source: 'src/lib.rs', lines 184:0-184:24 -/
@[reducible]
def Digits := Array Std.U64 2#usize

/-- [leanxmss::tweak_hash::{closure}]
    Source: 'src/lib.rs', lines 166:21-168:5 -/
def tweak_hash.closure (N : Std.Usize) :=
  Std.U8 × Std.U32 × Std.U32 × Array Std.U64 2#usize × Array Std.U64 N

/-- [leanxmss::verify::{closure}]
    Source: 'src/lib.rs', lines 136:41-138:5 -/
def verify.closure := Chains × Digits × Signature

end leanxmss
