#!/usr/bin/env python3
"""Temporary paired control for the three Xeon node rows affected by loop outlining."""
import fcntl
import hashlib
import json
import os
from pathlib import Path
import subprocess
import time

ROOT = Path.cwd()
OUT = ROOT / 'grid-evidence'
OUT.mkdir(exist_ok=True)
BASE = os.environ['BASE']
HEAD = os.environ['CANDIDATE']
DRIVER = subprocess.check_output(['git', 'rev-parse', 'HEAD'], text=True).strip()
ENV = dict(os.environ, CARGO_BUILD_JOBS='4', CARGO_TERM_COLOR='never', RUSTFLAGS='-C target-cpu=native')
ENV.pop('LEANVM_NUM_THREADS', None)
SCOPE = ['systemd-run', '--user', '--scope', '-q', '-p', 'MemoryMax=16G', '-p', 'MemorySwapMax=0']
records = []

def run(args, name, cwd=ROOT, env=ENV):
    with (OUT / name).open('w') as log:
        result = subprocess.run(list(map(str,args)), cwd=cwd, env=env, stdout=log, stderr=subprocess.STDOUT)
    if result.returncode:
        print((OUT / name).read_text()[-16000:], flush=True)
        raise RuntimeError(f'{name}: exit {result.returncode}')

for args,name in [(['rustc','-vV'],'compiler.txt'),(['lscpu'],'cpu.txt'),(['rustc','--print','cfg','-C','target-cpu=native'],'cfg.txt')]:
    run(args,name)
(OUT/'metadata.json').write_text(json.dumps(dict(base=BASE,head=HEAD,driver=DRIVER,flags=ENV['RUSTFLAGS'],affinity=sorted(os.sched_getaffinity(0)),phase='xeon-control',cases='2to1 higher node: rate1/1worker,rate2/1worker,rate1/8workers; first nodes generated by the same CLI are retained too'),indent=2))
patch = subprocess.check_output(['git','diff','4b3b3d1728b95b5acc2a7e9300303d9da4d9a76d','ceb165c833f16df100776168f84849fbe5e7ec2c','--','bins/leanvm/src/tracked.rs'])
(OUT/'diagnostic.patch').write_bytes(patch)
executables={}
for side,commit in [('base',BASE),('head',HEAD)]:
    cwd=Path('/tmp/grid-control-'+side)
    run(['git','worktree','add','--detach',cwd,commit],f'checkout-{side}.log')
    run(['git','apply',OUT/'diagnostic.patch'],f'apply-{side}.log',cwd)
    target=Path('/tmp/grid-control-target-'+side)
    run(SCOPE+['cargo','build','--release','-p','leanvm-cli'],f'build-{side}.log',cwd,dict(ENV,CARGO_TARGET_DIR=str(target)))
    executables[side]=target/'release/leanvm'
    run(['objdump','-d','-C',executables[side]],f'assembly-{side}.txt')
    run(['nm','-C',executables[side]],f'symbols-{side}.txt')
case='aggregate-leanxmss-100-2to1'
for rate,workers in [(1,1),(2,1),(1,8)]:
    for pair in range(5):
        for side in (['base','head'] if pair%2==0 else ['head','base']):
            name=f'{case}-rate{rate}-{workers}-{pair}-{side}'
            with open('/tmp/leanvm-bench.lock','a') as lock:
                fcntl.flock(lock,fcntl.LOCK_EX)
                deadline=time.monotonic()+900
                while os.getloadavg()[0]>=12:
                    if time.monotonic()>deadline: raise RuntimeError('load never below12')
                    time.sleep(5)
                before=os.getloadavg()
                run(SCOPE+[executables[side],'bench','--only',case,'--log-inv-rate',str(rate),'--repeat','1','--cooldown','0','--tracing'],name+'.log',env=dict(ENV,LEANVM_NUM_THREADS=str(workers),GRID_PROOFS=str(OUT/(name+'-proofs'))))
                after=os.getloadavg()
                record=dict(name=name,before=before,after=after,accepted=max(before[0],after[0])<=20)
                records.append(record)
                (OUT/'loads.json').write_text(json.dumps(records,indent=2))
                if not record['accepted']: raise RuntimeError(f'{name}: overloaded sample discarded')
        a=OUT/f'{case}-rate{rate}-{workers}-{pair}-base-proofs'
        b=OUT/f'{case}-rate{rate}-{workers}-{pair}-head-proofs'
        assert sorted(p.name for p in a.iterdir())==sorted(p.name for p in b.iterdir())
        for proof in a.iterdir():
            data=proof.read_bytes()
            assert data==(b/proof.name).read_bytes()
            with (OUT/'proof-equality.jsonl').open('a') as receipt:
                receipt.write(json.dumps(dict(case=case,rate=rate,workers=workers,pair=pair,file=proof.name,bytes=len(data),sha256=hashlib.sha256(data).hexdigest()))+'\n')
print('Three targeted Xeon node controls completed with literal paired proof equality and production verification.',flush=True)
