[package]
name = "leanvm_guest"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dev-dependencies]
primitives = { workspace = true, features = ["test-util"] }

[target.'cfg(not(all(target_arch = "riscv64", target_os = "none")))'.dependencies]
p3-binary-field = { git = "https://github.com/Plonky3/Plonky3", rev = "02b02337f09a9b2ddddba53ba2279bca22695958", features = ["wide-poly"] }
